In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [3]:
tf.compat.v1.set_random_seed(777)
g1 = tf.Graph()
with g1.as_default() as graph:
    
    X = tf.compat.v1.placeholder(tf.float32, shape=[None, 3])
    Y = tf.compat.v1.placeholder(tf.float32, shape=[None, 1])  
    
    W = tf.Variable(tf.compat.v1.random_normal([3, 1]), name = 'weight')
    b = tf.Variable(tf.compat.v1.random_normal([1]), name = 'bias')
        
    hypothesis = tf.matmul(X, W) + b
  
    cost = tf.reduce_mean(tf.square(hypothesis - Y))
    
    optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=1e-5)
    train = optimizer.minimize(cost)
    
    init_op = tf.compat.v1.global_variables_initializer()

In [6]:
sess = tf.compat.v1.Session(graph = g1)
sess.run(init_op)

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  49364.027 
Prediction: 
 [[-55.651993]
 [-67.117676]
 [-65.90801 ]
 [-73.41352 ]
 [-49.833942]
 [-39.167233]]
10 Cost:  3.1181958 
Prediction: 
 [[151.47734]
 [181.91129]
 [179.42479]
 [193.7602 ]
 [140.1209 ]
 [100.86882]]
20 Cost:  0.8532453 
Prediction: 
 [[152.87836]
 [183.59872]
 [181.08563]
 [195.56903]
 [141.40866]
 [101.81876]]
30 Cost:  0.8522002 
Prediction: 
 [[152.88608 ]
 [183.61105 ]
 [181.09619 ]
 [195.5807  ]
 [141.41867 ]
 [101.826744]]
40 Cost:  0.85126346 
Prediction: 
 [[152.88437]
 [183.61205]
 [181.09558]
 [195.5802 ]
 [141.42003]
 [101.82835]]
50 Cost:  0.85034275 
Prediction: 
 [[152.88263]
 [183.61293]
 [181.0949 ]
 [195.57962]
 [141.42134]
 [101.82988]]
60 Cost:  0.84941936 
Prediction: 
 [[152.88086 ]
 [183.61385 ]
 [181.09424 ]
 [195.57904 ]
 [141.42265 ]
 [101.831436]]
70 Cost:  0.8485074 
Prediction: 
 [[152.8791 ]
 [183.61472]
 [181.09354]
 [195.57845]
 [141.42393]
 [101.83296]]
80 Cost:  0.847598 
Prediction: 
 [[152.87735]
 [183.61562]
 [181.09

720 Cost:  0.79997426 
Prediction: 
 [[152.77695]
 [183.66704]
 [181.05428]
 [195.54398]
 [141.5003 ]
 [101.9221 ]]
730 Cost:  0.79937124 
Prediction: 
 [[152.77554]
 [183.66774]
 [181.05373]
 [195.5435 ]
 [141.50137]
 [101.9233 ]]
740 Cost:  0.79876906 
Prediction: 
 [[152.77415 ]
 [183.66849 ]
 [181.0532  ]
 [195.54301 ]
 [141.50244 ]
 [101.924515]]
750 Cost:  0.7981641 
Prediction: 
 [[152.77274]
 [183.6692 ]
 [181.05266]
 [195.54254]
 [141.50348]
 [101.92572]]
760 Cost:  0.7975809 
Prediction: 
 [[152.77135 ]
 [183.6699  ]
 [181.05212 ]
 [195.54205 ]
 [141.50453 ]
 [101.926926]]
770 Cost:  0.797 
Prediction: 
 [[152.76997]
 [183.67062]
 [181.05162]
 [195.5416 ]
 [141.5056 ]
 [101.92813]]
780 Cost:  0.79640204 
Prediction: 
 [[152.76857]
 [183.67134]
 [181.05107]
 [195.54109]
 [141.50664]
 [101.92931]]
790 Cost:  0.7958219 
Prediction: 
 [[152.7672 ]
 [183.67206]
 [181.05055]
 [195.54062]
 [141.50769]
 [101.93051]]
800 Cost:  0.7952545 
Prediction: 
 [[152.76581 ]
 [183.67273 ]
 [18

1520 Cost:  0.7617654 
Prediction: 
 [[152.67815 ]
 [183.71814 ]
 [181.01674 ]
 [195.50911 ]
 [141.57628 ]
 [102.006615]]
1530 Cost:  0.7613866 
Prediction: 
 [[152.67706 ]
 [183.7187  ]
 [181.01633 ]
 [195.50871 ]
 [141.57713 ]
 [102.007515]]
1540 Cost:  0.7610407 
Prediction: 
 [[152.67601 ]
 [183.71924 ]
 [181.01593 ]
 [195.5083  ]
 [141.57796 ]
 [102.008415]]
1550 Cost:  0.76066965 
Prediction: 
 [[152.67493 ]
 [183.71979 ]
 [181.0155  ]
 [195.5079  ]
 [141.57878 ]
 [102.009315]]
1560 Cost:  0.7603061 
Prediction: 
 [[152.67386]
 [183.72037]
 [181.01514]
 [195.50754]
 [141.57962]
 [102.01022]]
1570 Cost:  0.75993043 
Prediction: 
 [[152.6728  ]
 [183.72093 ]
 [181.01471 ]
 [195.50716 ]
 [141.58046 ]
 [102.011116]]
1580 Cost:  0.7595785 
Prediction: 
 [[152.67174]
 [183.72148]
 [181.01433]
 [195.50676]
 [141.58127]
 [102.012  ]]
1590 Cost:  0.75921196 
Prediction: 
 [[152.67068 ]
 [183.72203 ]
 [181.01392 ]
 [195.50638 ]
 [141.58212 ]
 [102.012886]]
1600 Cost:  0.7588722 
Prediction

In [9]:
print("Your score will be ", sess.run(hypothesis,
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[179.5035]]
Other scores will be  [[135.19328]
 [187.42741]]
