In [16]:
import tensorflow as tf
import numpy as np

In [5]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

g1 = tf.Graph()
with g1.as_default() as graph:
    
    X = tf.compat.v1.placeholder(tf.float32, shape=[None, 4])
    Y = tf.compat.v1.placeholder(tf.float32, shape=[None, 3])
    nb_calsses = 3
    
    W = tf.Variable(tf.compat.v1.random_normal([4, nb_calsses]), name = 'weight')
    b = tf.Variable(tf.compat.v1.random_normal([nb_calsses]), name = 'bias')
        
    hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
  
    cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.compat.v1.log(hypothesis), axis=1))
    
    optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.01)
    train = optimizer.minimize(cost)
    
    predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
    accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
    
    init_op = tf.compat.v1.global_variables_initializer()
    
sess = tf.compat.v1.Session(graph = g1)
sess.run(init_op)

In [20]:
for step in range(20001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
        print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

0 0.34861866
200 0.34340394
400 0.33836532
600 0.33349043
800 0.32876804
1000 0.32418826
1200 0.31974253
1400 0.31542322
1600 0.31122345
1800 0.307137
2000 0.30315825
2200 0.29928225
2400 0.2955041
2600 0.2918196
2800 0.2882249
3000 0.2847162
3200 0.28129017
3400 0.27794355
3600 0.27467355
3800 0.2714771
4000 0.26835182
4200 0.2652951
4400 0.2623046
4600 0.2593782
4800 0.2565137
5000 0.2537091
5200 0.2509625
5400 0.24827218
5600 0.24563631
5800 0.24305329
6000 0.24052164
6200 0.23803961
6400 0.23560596
6600 0.23321924
6800 0.23087803
7000 0.22858109
7200 0.22632736
7400 0.22411537
7600 0.22194423
7800 0.21981281
8000 0.21771987
8200 0.21566448
8400 0.21364574
8600 0.21166265
8800 0.20971432
9000 0.20779979
9200 0.2059182
9400 0.20406891
9600 0.20225087
9800 0.20046353
10000 0.19870596
10200 0.19697765
10400 0.19527762
10600 0.19360536
10800 0.19196029
11000 0.1903416
11200 0.18874876
11400 0.18718123
11600 0.18563831
11800 0.18411963
12000 0.18262435
12200 0.18115216
12400 0.17970243
1

In [25]:
a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
print(a)

print('-------------')

b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
print(b)

print('-------------')
c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
print(c)

print('-------------')

all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
print(all)

print('-------------')

[[3.6477447e-03 9.9634677e-01 5.4331663e-06]]
-------------
[[0.86650133 0.12027565 0.01322303]]
-------------
[[2.7186471e-09 1.7774751e-04 9.9982232e-01]]
-------------
[[3.64774792e-03 9.96346772e-01 5.43317674e-06]
 [8.66501331e-01 1.20275624e-01 1.32230287e-02]
 [2.71864709e-09 1.77747512e-04 9.99822319e-01]]
-------------
