In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [2]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, activation='linear', dtype='float32')
])

sgd = tf.optimizers.SGD(learning_rate=1e-5)
model.compile(optimizer=sgd, 
              loss='mean_squared_error',
              metrics=[])

model.fit(x_data, y_data, verbose=2, epochs=2001)

Train on 6 samples
Epoch 1/2001
6/6 - 1s - loss: 103492.6562
Epoch 2/2001
6/6 - 0s - loss: 38114.1367
Epoch 3/2001
6/6 - 0s - loss: 14038.0967
Epoch 4/2001
6/6 - 0s - loss: 5171.9478
Epoch 5/2001
6/6 - 0s - loss: 1906.9355
Epoch 6/2001
6/6 - 0s - loss: 704.5730
Epoch 7/2001
6/6 - 0s - loss: 261.7957
Epoch 8/2001
6/6 - 0s - loss: 98.7385
Epoch 9/2001
6/6 - 0s - loss: 38.6909
Epoch 10/2001
6/6 - 0s - loss: 16.5770
Epoch 11/2001
6/6 - 0s - loss: 8.4324
Epoch 12/2001
6/6 - 0s - loss: 5.4320
Epoch 13/2001
6/6 - 0s - loss: 4.3260
Epoch 14/2001
6/6 - 0s - loss: 3.9177
Epoch 15/2001
6/6 - 0s - loss: 3.7663
Epoch 16/2001
6/6 - 0s - loss: 3.7095
Epoch 17/2001
6/6 - 0s - loss: 3.6876
Epoch 18/2001
6/6 - 0s - loss: 3.6784
Epoch 19/2001
6/6 - 0s - loss: 3.6740
Epoch 20/2001
6/6 - 0s - loss: 3.6714
Epoch 21/2001
6/6 - 0s - loss: 3.6694
Epoch 22/2001
6/6 - 0s - loss: 3.6676
Epoch 23/2001
6/6 - 0s - loss: 3.6659
Epoch 24/2001
6/6 - 0s - loss: 3.6643
Epoch 25/2001
6/6 - 0s - loss: 3.6626
Epoch 26/2001


Epoch 213/2001
6/6 - 0s - loss: 3.3733
Epoch 214/2001
6/6 - 0s - loss: 3.3718
Epoch 215/2001
6/6 - 0s - loss: 3.3704
Epoch 216/2001
6/6 - 0s - loss: 3.3689
Epoch 217/2001
6/6 - 0s - loss: 3.3675
Epoch 218/2001
6/6 - 0s - loss: 3.3660
Epoch 219/2001
6/6 - 0s - loss: 3.3646
Epoch 220/2001
6/6 - 0s - loss: 3.3631
Epoch 221/2001
6/6 - 0s - loss: 3.3617
Epoch 222/2001
6/6 - 0s - loss: 3.3603
Epoch 223/2001
6/6 - 0s - loss: 3.3588
Epoch 224/2001
6/6 - 0s - loss: 3.3574
Epoch 225/2001
6/6 - 0s - loss: 3.3560
Epoch 226/2001
6/6 - 0s - loss: 3.3545
Epoch 227/2001
6/6 - 0s - loss: 3.3531
Epoch 228/2001
6/6 - 0s - loss: 3.3516
Epoch 229/2001
6/6 - 0s - loss: 3.3502
Epoch 230/2001
6/6 - 0s - loss: 3.3488
Epoch 231/2001
6/6 - 0s - loss: 3.3474
Epoch 232/2001
6/6 - 0s - loss: 3.3459
Epoch 233/2001
6/6 - 0s - loss: 3.3445
Epoch 234/2001
6/6 - 0s - loss: 3.3431
Epoch 235/2001
6/6 - 0s - loss: 3.3416
Epoch 236/2001
6/6 - 0s - loss: 3.3402
Epoch 237/2001
6/6 - 0s - loss: 3.3388
Epoch 238/2001
6/6 - 0s -

Epoch 424/2001
6/6 - 0s - loss: 3.0876
Epoch 425/2001
6/6 - 0s - loss: 3.0863
Epoch 426/2001
6/6 - 0s - loss: 3.0851
Epoch 427/2001
6/6 - 0s - loss: 3.0838
Epoch 428/2001
6/6 - 0s - loss: 3.0825
Epoch 429/2001
6/6 - 0s - loss: 3.0813
Epoch 430/2001
6/6 - 0s - loss: 3.0800
Epoch 431/2001
6/6 - 0s - loss: 3.0788
Epoch 432/2001
6/6 - 0s - loss: 3.0775
Epoch 433/2001
6/6 - 0s - loss: 3.0763
Epoch 434/2001
6/6 - 0s - loss: 3.0750
Epoch 435/2001
6/6 - 0s - loss: 3.0737
Epoch 436/2001
6/6 - 0s - loss: 3.0725
Epoch 437/2001
6/6 - 0s - loss: 3.0712
Epoch 438/2001
6/6 - 0s - loss: 3.0700
Epoch 439/2001
6/6 - 0s - loss: 3.0687
Epoch 440/2001
6/6 - 0s - loss: 3.0675
Epoch 441/2001
6/6 - 0s - loss: 3.0662
Epoch 442/2001
6/6 - 0s - loss: 3.0650
Epoch 443/2001
6/6 - 0s - loss: 3.0637
Epoch 444/2001
6/6 - 0s - loss: 3.0625
Epoch 445/2001
6/6 - 0s - loss: 3.0612
Epoch 446/2001
6/6 - 0s - loss: 3.0600
Epoch 447/2001
6/6 - 0s - loss: 3.0587
Epoch 448/2001
6/6 - 0s - loss: 3.0575
Epoch 449/2001
6/6 - 0s -

Epoch 635/2001
6/6 - 0s - loss: 2.8381
Epoch 636/2001
6/6 - 0s - loss: 2.8370
Epoch 637/2001
6/6 - 0s - loss: 2.8359
Epoch 638/2001
6/6 - 0s - loss: 2.8348
Epoch 639/2001
6/6 - 0s - loss: 2.8337
Epoch 640/2001
6/6 - 0s - loss: 2.8326
Epoch 641/2001
6/6 - 0s - loss: 2.8315
Epoch 642/2001
6/6 - 0s - loss: 2.8304
Epoch 643/2001
6/6 - 0s - loss: 2.8293
Epoch 644/2001
6/6 - 0s - loss: 2.8282
Epoch 645/2001
6/6 - 0s - loss: 2.8271
Epoch 646/2001
6/6 - 0s - loss: 2.8260
Epoch 647/2001
6/6 - 0s - loss: 2.8249
Epoch 648/2001
6/6 - 0s - loss: 2.8238
Epoch 649/2001
6/6 - 0s - loss: 2.8227
Epoch 650/2001
6/6 - 0s - loss: 2.8216
Epoch 651/2001
6/6 - 0s - loss: 2.8205
Epoch 652/2001
6/6 - 0s - loss: 2.8194
Epoch 653/2001
6/6 - 0s - loss: 2.8183
Epoch 654/2001
6/6 - 0s - loss: 2.8172
Epoch 655/2001
6/6 - 0s - loss: 2.8161
Epoch 656/2001
6/6 - 0s - loss: 2.8151
Epoch 657/2001
6/6 - 0s - loss: 2.8140
Epoch 658/2001
6/6 - 0s - loss: 2.8129
Epoch 659/2001
6/6 - 0s - loss: 2.8118
Epoch 660/2001
6/6 - 0s -

Epoch 846/2001
6/6 - 0s - loss: 2.6200
Epoch 847/2001
6/6 - 0s - loss: 2.6191
Epoch 848/2001
6/6 - 0s - loss: 2.6181
Epoch 849/2001
6/6 - 0s - loss: 2.6171
Epoch 850/2001
6/6 - 0s - loss: 2.6162
Epoch 851/2001
6/6 - 0s - loss: 2.6152
Epoch 852/2001
6/6 - 0s - loss: 2.6142
Epoch 853/2001
6/6 - 0s - loss: 2.6133
Epoch 854/2001
6/6 - 0s - loss: 2.6123
Epoch 855/2001
6/6 - 0s - loss: 2.6114
Epoch 856/2001
6/6 - 0s - loss: 2.6104
Epoch 857/2001
6/6 - 0s - loss: 2.6094
Epoch 858/2001
6/6 - 0s - loss: 2.6085
Epoch 859/2001
6/6 - 0s - loss: 2.6075
Epoch 860/2001
6/6 - 0s - loss: 2.6066
Epoch 861/2001
6/6 - 0s - loss: 2.6056
Epoch 862/2001
6/6 - 0s - loss: 2.6046
Epoch 863/2001
6/6 - 0s - loss: 2.6037
Epoch 864/2001
6/6 - 0s - loss: 2.6027
Epoch 865/2001
6/6 - 0s - loss: 2.6018
Epoch 866/2001
6/6 - 0s - loss: 2.6008
Epoch 867/2001
6/6 - 0s - loss: 2.5999
Epoch 868/2001
6/6 - 0s - loss: 2.5989
Epoch 869/2001
6/6 - 0s - loss: 2.5980
Epoch 870/2001
6/6 - 0s - loss: 2.5970
Epoch 871/2001
6/6 - 0s -

Epoch 1055/2001
6/6 - 0s - loss: 2.4310
Epoch 1056/2001
6/6 - 0s - loss: 2.4301
Epoch 1057/2001
6/6 - 0s - loss: 2.4293
Epoch 1058/2001
6/6 - 0s - loss: 2.4285
Epoch 1059/2001
6/6 - 0s - loss: 2.4276
Epoch 1060/2001
6/6 - 0s - loss: 2.4268
Epoch 1061/2001
6/6 - 0s - loss: 2.4259
Epoch 1062/2001
6/6 - 0s - loss: 2.4251
Epoch 1063/2001
6/6 - 0s - loss: 2.4242
Epoch 1064/2001
6/6 - 0s - loss: 2.4234
Epoch 1065/2001
6/6 - 0s - loss: 2.4226
Epoch 1066/2001
6/6 - 0s - loss: 2.4217
Epoch 1067/2001
6/6 - 0s - loss: 2.4209
Epoch 1068/2001
6/6 - 0s - loss: 2.4200
Epoch 1069/2001
6/6 - 0s - loss: 2.4192
Epoch 1070/2001
6/6 - 0s - loss: 2.4184
Epoch 1071/2001
6/6 - 0s - loss: 2.4175
Epoch 1072/2001
6/6 - 0s - loss: 2.4167
Epoch 1073/2001
6/6 - 0s - loss: 2.4158
Epoch 1074/2001
6/6 - 0s - loss: 2.4150
Epoch 1075/2001
6/6 - 0s - loss: 2.4142
Epoch 1076/2001
6/6 - 0s - loss: 2.4133
Epoch 1077/2001
6/6 - 0s - loss: 2.4125
Epoch 1078/2001
6/6 - 0s - loss: 2.4117
Epoch 1079/2001
6/6 - 0s - loss: 2.4108


Epoch 1260/2001
6/6 - 0s - loss: 2.2683
Epoch 1261/2001
6/6 - 0s - loss: 2.2675
Epoch 1262/2001
6/6 - 0s - loss: 2.2668
Epoch 1263/2001
6/6 - 0s - loss: 2.2661
Epoch 1264/2001
6/6 - 0s - loss: 2.2653
Epoch 1265/2001
6/6 - 0s - loss: 2.2646
Epoch 1266/2001
6/6 - 0s - loss: 2.2638
Epoch 1267/2001
6/6 - 0s - loss: 2.2631
Epoch 1268/2001
6/6 - 0s - loss: 2.2623
Epoch 1269/2001
6/6 - 0s - loss: 2.2616
Epoch 1270/2001
6/6 - 0s - loss: 2.2609
Epoch 1271/2001
6/6 - 0s - loss: 2.2601
Epoch 1272/2001
6/6 - 0s - loss: 2.2594
Epoch 1273/2001
6/6 - 0s - loss: 2.2587
Epoch 1274/2001
6/6 - 0s - loss: 2.2579
Epoch 1275/2001
6/6 - 0s - loss: 2.2572
Epoch 1276/2001
6/6 - 0s - loss: 2.2565
Epoch 1277/2001
6/6 - 0s - loss: 2.2557
Epoch 1278/2001
6/6 - 0s - loss: 2.2550
Epoch 1279/2001
6/6 - 0s - loss: 2.2542
Epoch 1280/2001
6/6 - 0s - loss: 2.2535
Epoch 1281/2001
6/6 - 0s - loss: 2.2528
Epoch 1282/2001
6/6 - 0s - loss: 2.2520
Epoch 1283/2001
6/6 - 0s - loss: 2.2513
Epoch 1284/2001
6/6 - 0s - loss: 2.2506


Epoch 1465/2001
6/6 - 0s - loss: 2.1252
Epoch 1466/2001
6/6 - 0s - loss: 2.1246
Epoch 1467/2001
6/6 - 0s - loss: 2.1239
Epoch 1468/2001
6/6 - 0s - loss: 2.1233
Epoch 1469/2001
6/6 - 0s - loss: 2.1226
Epoch 1470/2001
6/6 - 0s - loss: 2.1220
Epoch 1471/2001
6/6 - 0s - loss: 2.1213
Epoch 1472/2001
6/6 - 0s - loss: 2.1207
Epoch 1473/2001
6/6 - 0s - loss: 2.1200
Epoch 1474/2001
6/6 - 0s - loss: 2.1193
Epoch 1475/2001
6/6 - 0s - loss: 2.1187
Epoch 1476/2001
6/6 - 0s - loss: 2.1181
Epoch 1477/2001
6/6 - 0s - loss: 2.1174
Epoch 1478/2001
6/6 - 0s - loss: 2.1167
Epoch 1479/2001
6/6 - 0s - loss: 2.1161
Epoch 1480/2001
6/6 - 0s - loss: 2.1155
Epoch 1481/2001
6/6 - 0s - loss: 2.1148
Epoch 1482/2001
6/6 - 0s - loss: 2.1142
Epoch 1483/2001
6/6 - 0s - loss: 2.1135
Epoch 1484/2001
6/6 - 0s - loss: 2.1129
Epoch 1485/2001
6/6 - 0s - loss: 2.1122
Epoch 1486/2001
6/6 - 0s - loss: 2.1116
Epoch 1487/2001
6/6 - 0s - loss: 2.1109
Epoch 1488/2001
6/6 - 0s - loss: 2.1103
Epoch 1489/2001
6/6 - 0s - loss: 2.1096


Epoch 1670/2001
6/6 - 0s - loss: 1.9993
Epoch 1671/2001
6/6 - 0s - loss: 1.9987
Epoch 1672/2001
6/6 - 0s - loss: 1.9982
Epoch 1673/2001
6/6 - 0s - loss: 1.9976
Epoch 1674/2001
6/6 - 0s - loss: 1.9970
Epoch 1675/2001
6/6 - 0s - loss: 1.9964
Epoch 1676/2001
6/6 - 0s - loss: 1.9959
Epoch 1677/2001
6/6 - 0s - loss: 1.9953
Epoch 1678/2001
6/6 - 0s - loss: 1.9947
Epoch 1679/2001
6/6 - 0s - loss: 1.9941
Epoch 1680/2001
6/6 - 0s - loss: 1.9936
Epoch 1681/2001
6/6 - 0s - loss: 1.9930
Epoch 1682/2001
6/6 - 0s - loss: 1.9924
Epoch 1683/2001
6/6 - 0s - loss: 1.9918
Epoch 1684/2001
6/6 - 0s - loss: 1.9913
Epoch 1685/2001
6/6 - 0s - loss: 1.9907
Epoch 1686/2001
6/6 - 0s - loss: 1.9901
Epoch 1687/2001
6/6 - 0s - loss: 1.9896
Epoch 1688/2001
6/6 - 0s - loss: 1.9890
Epoch 1689/2001
6/6 - 0s - loss: 1.9884
Epoch 1690/2001
6/6 - 0s - loss: 1.9879
Epoch 1691/2001
6/6 - 0s - loss: 1.9873
Epoch 1692/2001
6/6 - 0s - loss: 1.9867
Epoch 1693/2001
6/6 - 0s - loss: 1.9861
Epoch 1694/2001
6/6 - 0s - loss: 1.9856


Epoch 1875/2001
6/6 - 0s - loss: 1.8884
Epoch 1876/2001
6/6 - 0s - loss: 1.8879
Epoch 1877/2001
6/6 - 0s - loss: 1.8874
Epoch 1878/2001
6/6 - 0s - loss: 1.8869
Epoch 1879/2001
6/6 - 0s - loss: 1.8863
Epoch 1880/2001
6/6 - 0s - loss: 1.8858
Epoch 1881/2001
6/6 - 0s - loss: 1.8853
Epoch 1882/2001
6/6 - 0s - loss: 1.8848
Epoch 1883/2001
6/6 - 0s - loss: 1.8843
Epoch 1884/2001
6/6 - 0s - loss: 1.8838
Epoch 1885/2001
6/6 - 0s - loss: 1.8833
Epoch 1886/2001
6/6 - 0s - loss: 1.8828
Epoch 1887/2001
6/6 - 0s - loss: 1.8823
Epoch 1888/2001
6/6 - 0s - loss: 1.8818
Epoch 1889/2001
6/6 - 0s - loss: 1.8813
Epoch 1890/2001
6/6 - 0s - loss: 1.8808
Epoch 1891/2001
6/6 - 0s - loss: 1.8803
Epoch 1892/2001
6/6 - 0s - loss: 1.8798
Epoch 1893/2001
6/6 - 0s - loss: 1.8793
Epoch 1894/2001
6/6 - 0s - loss: 1.8788
Epoch 1895/2001
6/6 - 0s - loss: 1.8783
Epoch 1896/2001
6/6 - 0s - loss: 1.8778
Epoch 1897/2001
6/6 - 0s - loss: 1.8773
Epoch 1898/2001
6/6 - 0s - loss: 1.8768
Epoch 1899/2001
6/6 - 0s - loss: 1.8763


In [3]:
print("Your score will be ", model.predict([[100, 70, 101]]))
print("Other scores will be ", model.predict([[60, 70, 110], [90, 100, 80]]))

Your score will be  [[186.75528]]
Other scores will be  [[150.9692 ]
 [180.47682]]
