In [45]:
import tensorflow as tf
import numpy as np
tf.compat.v1.set_random_seed(777)

In [2]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [40]:
g1 = tf.Graph()
with g1.as_default() as graph:
    
    X = tf.compat.v1.placeholder("float", [None, 3])
    Y = tf.compat.v1.placeholder("float", [None, 3])
    
    W = tf.Variable(tf.compat.v1.random_normal([3, 3]), name = 'weight')
    b = tf.Variable(tf.compat.v1.random_normal([3]), name = 'bias')
        
    logits = tf.matmul(X, W + b)
    
    hypothesis = tf.nn.softmax(logits)
    cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.compat.v1.log(hypothesis), axis=1))

    prediction = tf.argmax(hypothesis, 1)
    is_correct = tf.equal(prediction, tf.argmax(Y, 1))
    accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
    
    optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
    
    init_op = tf.compat.v1.global_variables_initializer()
    
sess = tf.compat.v1.Session(graph = g1)
sess.run(init_op)

In [41]:
for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y:y_data})
    print(step, cost_val, W_val)

0 9.510953 [[ 0.43313843  0.45379338 -0.8515958 ]
 [-0.9558495   2.179485    2.082365  ]
 [-0.06406148  0.356137   -1.3240095 ]]
1 8.441467 [[ 0.4581382   0.4536123  -0.87641454]
 [-0.79335     2.220819    1.8785316 ]
 [ 0.09843829  0.37879792 -1.5091702 ]]
2 6.0573783 [[ 0.48313525  0.39344892 -0.8412482 ]
 [-0.6308559   1.9637438   1.9731128 ]
 [ 0.26093468  0.13199289 -1.4248616 ]]
3 4.9571953 [[ 0.50724524  0.42628422 -0.89819354]
 [-0.47015357  2.127994    1.6481602 ]
 [ 0.4191653   0.30216578 -1.753265  ]]
4 3.451249 [[ 0.52899307  0.36744246 -0.86109966]
 [-0.31446183  1.8731622   1.7473004 ]
 [ 0.567397    0.06689091 -1.6662219 ]]
5 3.6380098 [[ 0.46482247  0.40184778 -0.83133435]
 [-0.55453986  2.0396264   1.8209143 ]
 [ 0.31490508  0.2490145  -1.5958536 ]]
6 4.06907 [[ 0.4882036   0.3528372  -0.8057049 ]
 [-0.39541465  1.8206676   1.8807478 ]
 [ 0.47021922  0.03554448 -1.5376977 ]]
7 2.8191423 [[ 0.49011824  0.38950837 -0.84429073]
 [-0.29180837  1.9936845   1.6041245 ]
 [ 0.

 [-0.12345611  0.7512687  -1.6597462 ]]
120 1.4522977 [[-0.684137    0.20358808  0.51588494]
 [ 0.9910031   1.4715207   0.8434769 ]
 [ 0.03767576  0.63805765 -1.707667  ]]
121 3.3326652 [[-0.7268745   0.23472984  0.52748066]
 [ 0.8251909   1.6258006   0.85500914]
 [-0.14460701  0.8005456  -1.6878722 ]]
122 2.7807977 [[-0.70215756  0.18733323  0.55016035]
 [ 0.9870288   1.4030887   0.91588324]
 [ 0.01740329  0.57666594 -1.6260028 ]]
123 2.1788201 [[-0.6972163   0.2239665   0.5085858 ]
 [ 1.0753832   1.575976    0.6546415 ]
 [ 0.08156005  0.7609266  -1.8744203 ]]
124 2.931565 [[-0.7374104   0.22872885  0.5440176 ]
 [ 0.93220246  1.6235619   0.7502364 ]
 [-0.05778246  0.81512475 -1.7892759 ]]
125 3.357306 [[-0.714013    0.17399065  0.57535833]
 [ 1.0906432   1.3789625   0.83639497]
 [ 0.10140986  0.57626045 -1.7096039 ]]
126 2.697017 [[-0.77179104  0.21103813  0.59608895]
 [ 0.8614509   1.5528882   0.89166164]
 [-0.14250746  0.76280284 -1.652229  ]]
127 1.1092043 [[-0.74707973  0.20594631

In [42]:
print("Prediction : ", sess.run(prediction, feed_dict={X: x_test}))
print("Accuracy : ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

Prediction :  [2 2 2]
Accuracy :  1.0


In [59]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

g2 = tf.Graph()
with g2.as_default() as graph:
    
    xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

    xy = min_max_scaler(xy)
    
    x_data = xy[:, 0:-1]
    y_data = xy[:, [-1]]

    X = tf.compat.v1.placeholder(tf.float32, shape=[None, 4])
    Y = tf.compat.v1.placeholder(tf.float32, shape=[None, 1])

    W = tf.Variable(tf.compat.v1.random_normal([4, 1]), name='weight')
    b = tf.Variable(tf.compat.v1.random_normal([1]), name='bias')

    hypothesis = tf.matmul(X, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - Y))

    optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=1e-2)
    train = optimizer.minimize(cost)

    init_op = tf.compat.v1.global_variables_initializer()
    
sess = tf.compat.v1.Session(graph = g2)
sess.run(init_op)

In [60]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  5.1218586 
Prediction:
 [[-1.8874949]
 [-2.0111322]
 [-1.8052337]
 [-1.6275452]
 [-1.6757625]
 [-1.6384974]
 [-1.4422476]
 [-1.60106  ]]
1 Cost:  4.738823 
Prediction:
 [[-1.7732561]
 [-1.8996888]
 [-1.7121365]
 [-1.5551515]
 [-1.590316 ]
 [-1.5558879]
 [-1.386164 ]
 [-1.545735 ]]
2 Cost:  4.384511 
Prediction:
 [[-1.6634028]
 [-1.7925103]
 [-1.6225982]
 [-1.4855201]
 [-1.5081353]
 [-1.4764347]
 [-1.3322095]
 [-1.4925063]]
3 Cost:  4.05677 
Prediction:
 [[-1.5577676]
 [-1.6894335]
 [-1.5364829]
 [-1.4185457]
 [-1.4290956]
 [-1.4000168]
 [-1.2803028]
 [-1.4412937]]
4 Cost:  3.7536058 
Prediction:
 [[-1.4561892]
 [-1.5903016]
 [-1.4536598]
 [-1.3541266]
 [-1.3530769]
 [-1.3265183]
 [-1.2303656]
 [-1.3920203]]
5 Cost:  3.4731755 
Prediction:
 [[-1.3585119]
 [-1.494964 ]
 [-1.3740029]
 [-1.292165 ]
 [-1.2799637]
 [-1.2558277]
 [-1.1823229]
 [-1.3446121]]
6 Cost:  3.2137742 
Prediction:
 [[-1.2645872]
 [-1.4032755]
 [-1.2973913]
 [-1.2325674]
 [-1.2096448]
 [-1.1878372]
 [-1.136102

62 Cost:  0.05311632 
Prediction:
 [[ 0.8173317 ]
 [ 0.6397096 ]
 [ 0.41278592]
 [ 0.10207808]
 [ 0.36070952]
 [ 0.33162275]
 [-0.09215195]
 [-0.26556998]]
63 Cost:  0.050026327 
Prediction:
 [[ 0.82714903]
 [ 0.6495547 ]
 [ 0.42109266]
 [ 0.10864973]
 [ 0.36835167]
 [ 0.3390396 ]
 [-0.08683266]
 [-0.26024258]]
64 Cost:  0.04716514 
Prediction:
 [[ 0.83657634]
 [ 0.65901935]
 [ 0.42908195]
 [ 0.11497465]
 [ 0.37570253]
 [ 0.34617487]
 [-0.08170426]
 [-0.2551034 ]]
65 Cost:  0.04451561 
Prediction:
 [[ 0.8456286 ]
 [ 0.66811836]
 [ 0.4367657 ]
 [ 0.12106234]
 [ 0.3827732 ]
 [ 0.35303918]
 [-0.07675943]
 [-0.25014538]]
66 Cost:  0.04206185 
Prediction:
 [[ 0.8543206 ]
 [ 0.67686564]
 [ 0.44415587]
 [ 0.12692192]
 [ 0.3895744 ]
 [ 0.35964316]
 [-0.07199116]
 [-0.2453616 ]]
67 Cost:  0.03978923 
Prediction:
 [[ 0.86266583]
 [ 0.68527454]
 [ 0.45126355]
 [ 0.13256195]
 [ 0.39611644]
 [ 0.36599636]
 [-0.06739283]
 [-0.24074547]]
68 Cost:  0.037684176 
Prediction:
 [[ 0.8706776 ]
 [ 0.6933578

122 Cost:  0.010701711 
Prediction:
 [[ 1.0365609 ]
 [ 0.8687241 ]
 [ 0.6091043 ]
 [ 0.26154163]
 [ 0.54209435]
 [ 0.50864017]
 [ 0.04472475]
 [-0.12603699]]
123 Cost:  0.010643513 
Prediction:
 [[ 1.0372093 ]
 [ 0.869584  ]
 [ 0.6099041 ]
 [ 0.26227456]
 [ 0.54284984]
 [ 0.50939643]
 [ 0.0455011 ]
 [-0.12520382]]
124 Cost:  0.010587621 
Prediction:
 [[ 1.0378209 ]
 [ 0.87040746]
 [ 0.6106734 ]
 [ 0.26298344]
 [ 0.5435773 ]
 [ 0.5101255 ]
 [ 0.04625829]
 [-0.12438984]]
125 Cost:  0.010533871 
Prediction:
 [[ 1.0383977 ]
 [ 0.8711955 ]
 [ 0.6114133 ]
 [ 0.2636693 ]
 [ 0.54427785]
 [ 0.51082826]
 [ 0.046997  ]
 [-0.12359437]]
126 Cost:  0.010482115 
Prediction:
 [[ 1.0389407 ]
 [ 0.87195   ]
 [ 0.6121248 ]
 [ 0.26433295]
 [ 0.5449523 ]
 [ 0.5115057 ]
 [ 0.04771793]
 [-0.12281674]]
127 Cost:  0.010432215 
Prediction:
 [[ 1.0394514 ]
 [ 0.87267166]
 [ 0.61280894]
 [ 0.26497516]
 [ 0.54560155]
 [ 0.5121591 ]
 [ 0.04842173]
 [-0.12205632]]
128 Cost:  0.010384049 
Prediction:
 [[ 1.0399309 ]


180 Cost:  0.008859845 
Prediction:
 [[ 1.041911  ]
 [ 0.8855866 ]
 [ 0.6277302 ]
 [ 0.282184  ]
 [ 0.5604662 ]
 [ 0.5277717 ]
 [ 0.07185279]
 [-0.09584779]]
181 Cost:  0.008838395 
Prediction:
 [[ 1.0417384 ]
 [ 0.8855927 ]
 [ 0.6278098 ]
 [ 0.28234708]
 [ 0.56056184]
 [ 0.52788556]
 [ 0.07215433]
 [-0.09549939]]
182 Cost:  0.00881709 
Prediction:
 [[ 1.0415633 ]
 [ 0.88559496]
 [ 0.6278862 ]
 [ 0.2825076 ]
 [ 0.5606545 ]
 [ 0.52799654]
 [ 0.07245325]
 [-0.09515385]]
183 Cost:  0.008795927 
Prediction:
 [[ 1.0413852 ]
 [ 0.8855937 ]
 [ 0.62795955]
 [ 0.28266543]
 [ 0.5607443 ]
 [ 0.5281048 ]
 [ 0.07274961]
 [-0.09481109]]
184 Cost:  0.008774911 
Prediction:
 [[ 1.0412045 ]
 [ 0.8855889 ]
 [ 0.6280298 ]
 [ 0.28282082]
 [ 0.5608315 ]
 [ 0.5282102 ]
 [ 0.07304353]
 [-0.09447104]]
185 Cost:  0.008754034 
Prediction:
 [[ 1.0410212 ]
 [ 0.88558084]
 [ 0.6280973 ]
 [ 0.28297383]
 [ 0.560916  ]
 [ 0.5283131 ]
 [ 0.07333499]
 [-0.09413362]]
186 Cost:  0.008733297 
Prediction:
 [[ 1.0408354 ]
 

240 Cost:  0.0077826707 
Prediction:
 [[ 1.0294669 ]
 [ 0.88247883]
 [ 0.62940085]
 [ 0.28926167]
 [ 0.5633708 ]
 [ 0.53174716]
 [ 0.08692504]
 [-0.07835739]]
241 Cost:  0.007767754 
Prediction:
 [[ 1.0292552 ]
 [ 0.8824001 ]
 [ 0.62940264]
 [ 0.28935453]
 [ 0.56339556]
 [ 0.53178865]
 [ 0.08714187]
 [-0.07810675]]
242 Cost:  0.0077529303 
Prediction:
 [[ 1.0290439 ]
 [ 0.88232136]
 [ 0.6294042 ]
 [ 0.28944695]
 [ 0.56342006]
 [ 0.5318298 ]
 [ 0.08735788]
 [-0.07785708]]
243 Cost:  0.007738182 
Prediction:
 [[ 1.028833  ]
 [ 0.8822421 ]
 [ 0.6294054 ]
 [ 0.289539  ]
 [ 0.56344414]
 [ 0.5318706 ]
 [ 0.08757314]
 [-0.07760839]]
244 Cost:  0.007723525 
Prediction:
 [[ 1.0286227 ]
 [ 0.8821627 ]
 [ 0.62940633]
 [ 0.28963065]
 [ 0.5634681 ]
 [ 0.531911  ]
 [ 0.08778764]
 [-0.07736066]]
245 Cost:  0.007708952 
Prediction:
 [[ 1.0284128 ]
 [ 0.88208294]
 [ 0.6294069 ]
 [ 0.2897219 ]
 [ 0.5634918 ]
 [ 0.53195107]
 [ 0.08800137]
 [-0.0771139 ]]
246 Cost:  0.0076944623 
Prediction:
 [[ 1.0282035

 [-0.06523213]]
299 Cost:  0.007033284 
Prediction:
 [[ 1.017917  ]
 [ 0.87765825]
 [ 0.6291743 ]
 [ 0.29422426]
 [ 0.5645269 ]
 [ 0.53380436]
 [ 0.09857608]
 [-0.06502816]]
300 Cost:  0.007022609 
Prediction:
 [[ 1.0177394 ]
 [ 0.87757635]
 [ 0.62916714]
 [ 0.29430157]
 [ 0.56454355]
 [ 0.5338348 ]
 [ 0.09875609]
 [-0.06482487]]
301 Cost:  0.007011993 
Prediction:
 [[ 1.0175624 ]
 [ 0.87749463]
 [ 0.6291601 ]
 [ 0.29437876]
 [ 0.5645602 ]
 [ 0.5338652 ]
 [ 0.0989356 ]
 [-0.06462225]]
302 Cost:  0.0070014354 
Prediction:
 [[ 1.017386  ]
 [ 0.87741286]
 [ 0.6291529 ]
 [ 0.29445565]
 [ 0.5645766 ]
 [ 0.53389543]
 [ 0.09911457]
 [-0.06442032]]
303 Cost:  0.0069909375 
Prediction:
 [[ 1.0172104 ]
 [ 0.8773313 ]
 [ 0.62914574]
 [ 0.29453248]
 [ 0.56459314]
 [ 0.5339256 ]
 [ 0.09929305]
 [-0.06421906]]
304 Cost:  0.0069805044 
Prediction:
 [[ 1.0170352 ]
 [ 0.87724984]
 [ 0.62913847]
 [ 0.29460904]
 [ 0.56460965]
 [ 0.5339557 ]
 [ 0.09947097]
 [-0.06401847]]
305 Cost:  0.006970119 
Predictio

355 Cost:  0.006517781 
Prediction:
 [[ 1.0088896 ]
 [ 0.8731883 ]
 [ 0.62872106]
 [ 0.2983023 ]
 [ 0.5653979 ]
 [ 0.53538036]
 [ 0.10790902]
 [-0.05461898]]
356 Cost:  0.0065099336 
Prediction:
 [[ 1.0087445 ]
 [ 0.87311083]
 [ 0.6287122 ]
 [ 0.29837087]
 [ 0.5654125 ]
 [ 0.53540653]
 [ 0.10806274]
 [-0.05444995]]
357 Cost:  0.0065021347 
Prediction:
 [[ 1.0086    ]
 [ 0.8730334 ]
 [ 0.62870336]
 [ 0.29843926]
 [ 0.5654273 ]
 [ 0.5354326 ]
 [ 0.10821604]
 [-0.05428147]]
358 Cost:  0.006494376 
Prediction:
 [[ 1.0084562 ]
 [ 0.87295616]
 [ 0.6286945 ]
 [ 0.29850757]
 [ 0.565442  ]
 [ 0.53545845]
 [ 0.10836892]
 [-0.05411352]]
359 Cost:  0.0064866524 
Prediction:
 [[ 1.0083127 ]
 [ 0.8728788 ]
 [ 0.6286855 ]
 [ 0.2985757 ]
 [ 0.5654565 ]
 [ 0.5354843 ]
 [ 0.10852136]
 [-0.05394613]]
360 Cost:  0.006478976 
Prediction:
 [[ 1.0081699 ]
 [ 0.87280184]
 [ 0.6286766 ]
 [ 0.29864377]
 [ 0.5654711 ]
 [ 0.5355102 ]
 [ 0.10867336]
 [-0.05377928]]
361 Cost:  0.0064713424 
Prediction:
 [[ 1.008027

408 Cost:  0.006154818 
Prediction:
 [[ 1.0019025 ]
 [ 0.8691993 ]
 [ 0.6282291 ]
 [ 0.3017521 ]
 [ 0.5661431 ]
 [ 0.53667814]
 [ 0.11549942]
 [-0.04637745]]
409 Cost:  0.006148898 
Prediction:
 [[ 1.0017836 ]
 [ 0.86912626]
 [ 0.62821954]
 [ 0.30181378]
 [ 0.5661565 ]
 [ 0.5367011 ]
 [ 0.11563231]
 [-0.0462352 ]]
410 Cost:  0.006143013 
Prediction:
 [[ 1.0016651 ]
 [ 0.8690534 ]
 [ 0.6282098 ]
 [ 0.30187532]
 [ 0.5661699 ]
 [ 0.536724  ]
 [ 0.11576483]
 [-0.0460934 ]]
411 Cost:  0.0061371597 
Prediction:
 [[ 1.0015471 ]
 [ 0.86898065]
 [ 0.6282002 ]
 [ 0.30193672]
 [ 0.5661834 ]
 [ 0.53674674]
 [ 0.11589701]
 [-0.04595207]]
412 Cost:  0.006131337 
Prediction:
 [[ 1.0014294 ]
 [ 0.86890805]
 [ 0.6281904 ]
 [ 0.301998  ]
 [ 0.56619674]
 [ 0.5367695 ]
 [ 0.11602882]
 [-0.0458112 ]]
413 Cost:  0.0061255405 
Prediction:
 [[ 1.0013124 ]
 [ 0.8688354 ]
 [ 0.6281808 ]
 [ 0.30205923]
 [ 0.56621015]
 [ 0.5367923 ]
 [ 0.11616029]
 [-0.04567077]]
414 Cost:  0.0061197774 
Prediction:
 [[ 1.0011955

467 Cost:  0.0058531985 
Prediction:
 [[ 0.9956054 ]
 [ 0.86504215]
 [ 0.6276449 ]
 [ 0.30519217]
 [ 0.5669024 ]
 [ 0.5379438 ]
 [ 0.12275558]
 [-0.03872626]]
468 Cost:  0.005848828 
Prediction:
 [[ 0.99551046]
 [ 0.86497426]
 [ 0.6276349 ]
 [ 0.30524716]
 [ 0.5669147 ]
 [ 0.5379638 ]
 [ 0.12286892]
 [-0.03860876]]
469 Cost:  0.0058444804 
Prediction:
 [[ 0.9954158 ]
 [ 0.86490643]
 [ 0.62762475]
 [ 0.30530205]
 [ 0.56692696]
 [ 0.5379838 ]
 [ 0.12298194]
 [-0.03849164]]
470 Cost:  0.0058401525 
Prediction:
 [[ 0.9953216 ]
 [ 0.86483866]
 [ 0.6276146 ]
 [ 0.30535686]
 [ 0.5669392 ]
 [ 0.5380037 ]
 [ 0.12309466]
 [-0.03837491]]
471 Cost:  0.0058358503 
Prediction:
 [[ 0.99522793]
 [ 0.8647708 ]
 [ 0.6276045 ]
 [ 0.3054115 ]
 [ 0.56695145]
 [ 0.5380236 ]
 [ 0.12320706]
 [-0.03825855]]
472 Cost:  0.0058315666 
Prediction:
 [[ 0.9951343 ]
 [ 0.86470336]
 [ 0.6275944 ]
 [ 0.30546615]
 [ 0.56696373]
 [ 0.5380434 ]
 [ 0.12331917]
 [-0.03814255]]
473 Cost:  0.0058273016 
Prediction:
 [[ 0.9950

527 Cost:  0.005625829 
Prediction:
 [[ 0.9905133 ]
 [ 0.8611101 ]
 [ 0.62703085]
 [ 0.308313  ]
 [ 0.5676068 ]
 [ 0.53906626]
 [ 0.12904806]
 [-0.03230744]]
528 Cost:  0.0056225755 
Prediction:
 [[ 0.99043816]
 [ 0.861047  ]
 [ 0.62702054]
 [ 0.3083621 ]
 [ 0.567618  ]
 [ 0.53908366]
 [ 0.1291447 ]
 [-0.03221063]]
529 Cost:  0.0056193373 
Prediction:
 [[ 0.99036324]
 [ 0.8609841 ]
 [ 0.62701017]
 [ 0.30841112]
 [ 0.56762916]
 [ 0.5391011 ]
 [ 0.12924108]
 [-0.03211414]]
530 Cost:  0.0056161154 
Prediction:
 [[ 0.99028873]
 [ 0.8609211 ]
 [ 0.6269998 ]
 [ 0.30846   ]
 [ 0.56764036]
 [ 0.5391184 ]
 [ 0.12933724]
 [-0.03201796]]
531 Cost:  0.00561291 
Prediction:
 [[ 0.99021435]
 [ 0.8608583 ]
 [ 0.6269895 ]
 [ 0.3085088 ]
 [ 0.5676515 ]
 [ 0.5391358 ]
 [ 0.1294331 ]
 [-0.03192209]]
532 Cost:  0.005609718 
Prediction:
 [[ 0.99014044]
 [ 0.86079556]
 [ 0.6269792 ]
 [ 0.3085575 ]
 [ 0.56766266]
 [ 0.53915304]
 [ 0.12952873]
 [-0.03182652]]
533 Cost:  0.005606545 
Prediction:
 [[ 0.9900668 

586 Cost:  0.0054579703 
Prediction:
 [[ 0.9865526 ]
 [ 0.85751975]
 [ 0.62642086]
 [ 0.31105733]
 [ 0.5682386 ]
 [ 0.5400312 ]
 [ 0.13433841]
 [-0.0270969 ]]
587 Cost:  0.0054555065 
Prediction:
 [[ 0.9864933 ]
 [ 0.8574613 ]
 [ 0.6264104 ]
 [ 0.31110126]
 [ 0.5682488 ]
 [ 0.5400465 ]
 [ 0.13442126]
 [-0.02701681]]
588 Cost:  0.005453054 
Prediction:
 [[ 0.9864343 ]
 [ 0.85740274]
 [ 0.6264002 ]
 [ 0.3111452 ]
 [ 0.5682591 ]
 [ 0.54006183]
 [ 0.13450393]
 [-0.02693699]]
589 Cost:  0.00545061 
Prediction:
 [[ 0.9863752 ]
 [ 0.8573444 ]
 [ 0.62638974]
 [ 0.311189  ]
 [ 0.56826925]
 [ 0.540077  ]
 [ 0.13458635]
 [-0.02685741]]
590 Cost:  0.0054481803 
Prediction:
 [[ 0.9863167 ]
 [ 0.85728604]
 [ 0.6263795 ]
 [ 0.3112327 ]
 [ 0.56827945]
 [ 0.5400923 ]
 [ 0.13466857]
 [-0.02677811]]
591 Cost:  0.005445756 
Prediction:
 [[ 0.9862582 ]
 [ 0.85722774]
 [ 0.62636924]
 [ 0.31127638]
 [ 0.5682896 ]
 [ 0.54010737]
 [ 0.13475057]
 [-0.02669904]]
592 Cost:  0.0054433453 
Prediction:
 [[ 0.9862000

647 Cost:  0.005326175 
Prediction:
 [[ 0.9833399 ]
 [ 0.85407996]
 [ 0.62579477]
 [ 0.31359822]
 [ 0.5688338 ]
 [ 0.5409049 ]
 [ 0.13902244]
 [-0.02265218]]
648 Cost:  0.0053242957 
Prediction:
 [[ 0.98329365]
 [ 0.8540256 ]
 [ 0.6257846 ]
 [ 0.3136376 ]
 [ 0.5688431 ]
 [ 0.54091823]
 [ 0.13909331]
 [-0.02258629]]
649 Cost:  0.0053224294 
Prediction:
 [[ 0.9832477 ]
 [ 0.85397166]
 [ 0.6257744 ]
 [ 0.31367686]
 [ 0.5688524 ]
 [ 0.54093164]
 [ 0.139164  ]
 [-0.02252061]]
650 Cost:  0.0053205667 
Prediction:
 [[ 0.98320174]
 [ 0.8539175 ]
 [ 0.6257642 ]
 [ 0.31371605]
 [ 0.56886166]
 [ 0.5409448 ]
 [ 0.13923451]
 [-0.02245514]]
651 Cost:  0.0053187134 
Prediction:
 [[ 0.9831561 ]
 [ 0.85386354]
 [ 0.62575406]
 [ 0.3137552 ]
 [ 0.5688709 ]
 [ 0.54095817]
 [ 0.13930485]
 [-0.02238988]]
652 Cost:  0.0053168708 
Prediction:
 [[ 0.98311067]
 [ 0.8538097 ]
 [ 0.6257439 ]
 [ 0.3137943 ]
 [ 0.5688802 ]
 [ 0.5409715 ]
 [ 0.139375  ]
 [-0.02232482]]
653 Cost:  0.005315034 
Prediction:
 [[ 0.98306

709 Cost:  0.005223726 
Prediction:
 [[ 0.9808142 ]
 [ 0.8508502 ]
 [ 0.6251719 ]
 [ 0.31590995]
 [ 0.56938374]
 [ 0.5416819 ]
 [ 0.14309546]
 [-0.01893905]]
710 Cost:  0.0052222833 
Prediction:
 [[ 0.9807786 ]
 [ 0.8508003 ]
 [ 0.625162  ]
 [ 0.31594512]
 [ 0.56939214]
 [ 0.5416935 ]
 [ 0.14315611]
 [-0.01888496]]
711 Cost:  0.005220845 
Prediction:
 [[ 0.9807434 ]
 [ 0.8507503 ]
 [ 0.6251521 ]
 [ 0.31598035]
 [ 0.5694006 ]
 [ 0.5417052 ]
 [ 0.14321661]
 [-0.01883102]]
712 Cost:  0.0052194144 
Prediction:
 [[ 0.9807083 ]
 [ 0.85070056]
 [ 0.6251423 ]
 [ 0.31601548]
 [ 0.5694091 ]
 [ 0.5417169 ]
 [ 0.14327696]
 [-0.01877727]]
713 Cost:  0.00521799 
Prediction:
 [[ 0.9806732 ]
 [ 0.8506506 ]
 [ 0.62513226]
 [ 0.31605047]
 [ 0.5694174 ]
 [ 0.5417285 ]
 [ 0.14333715]
 [-0.01872369]]
714 Cost:  0.005216568 
Prediction:
 [[ 0.9806382 ]
 [ 0.85060096]
 [ 0.6251224 ]
 [ 0.31608546]
 [ 0.56942576]
 [ 0.54174006]
 [ 0.14339721]
 [-0.01867027]]
715 Cost:  0.005215153 
Prediction:
 [[ 0.98060346]

761 Cost:  0.005155935 
Prediction:
 [[ 0.97916037]
 [ 0.84833586]
 [ 0.6246641 ]
 [ 0.3176624 ]
 [ 0.56980526]
 [ 0.5422582 ]
 [ 0.1460585 ]
 [-0.01634081]]
762 Cost:  0.0051547633 
Prediction:
 [[ 0.9791323 ]
 [ 0.848289  ]
 [ 0.62465453]
 [ 0.3176945 ]
 [ 0.569813  ]
 [ 0.54226863]
 [ 0.14611185]
 [-0.0162949 ]]
763 Cost:  0.0051535987 
Prediction:
 [[ 0.9791041 ]
 [ 0.8482424 ]
 [ 0.624645  ]
 [ 0.31772667]
 [ 0.5698208 ]
 [ 0.5422792 ]
 [ 0.14616506]
 [-0.01624914]]
764 Cost:  0.005152433 
Prediction:
 [[ 0.97907627]
 [ 0.8481959 ]
 [ 0.6246353 ]
 [ 0.31775874]
 [ 0.56982845]
 [ 0.5422896 ]
 [ 0.14621815]
 [-0.01620352]]
765 Cost:  0.0051512797 
Prediction:
 [[ 0.9790484 ]
 [ 0.8481494 ]
 [ 0.6246258 ]
 [ 0.3177907 ]
 [ 0.56983626]
 [ 0.5423    ]
 [ 0.14627111]
 [-0.01615804]]
766 Cost:  0.0051501263 
Prediction:
 [[ 0.9790207 ]
 [ 0.848103  ]
 [ 0.62461615]
 [ 0.31782266]
 [ 0.56984395]
 [ 0.5423104 ]
 [ 0.14632395]
 [-0.01611271]]
767 Cost:  0.005148981 
Prediction:
 [[ 0.978993

 [-0.01367482]]
826 Cost:  0.005088549 
Prediction:
 [[ 0.9775732 ]
 [ 0.84542656]
 [ 0.6240532 ]
 [ 0.31964174]
 [ 0.5702861 ]
 [ 0.5428956 ]
 [ 0.14927033]
 [-0.01363726]]
827 Cost:  0.005087633 
Prediction:
 [[ 0.97755253]
 [ 0.84538364]
 [ 0.62404394]
 [ 0.31967053]
 [ 0.57029307]
 [ 0.54290473]
 [ 0.14931592]
 [-0.01359981]]
828 Cost:  0.0050867256 
Prediction:
 [[ 0.9775318 ]
 [ 0.845341  ]
 [ 0.6240349 ]
 [ 0.3196993 ]
 [ 0.57030016]
 [ 0.5429139 ]
 [ 0.1493614 ]
 [-0.01356248]]
829 Cost:  0.0050858203 
Prediction:
 [[ 0.97751117]
 [ 0.84529823]
 [ 0.6240257 ]
 [ 0.3197279 ]
 [ 0.57030714]
 [ 0.542923  ]
 [ 0.14940678]
 [-0.01352527]]
830 Cost:  0.005084916 
Prediction:
 [[ 0.97749066]
 [ 0.8452556 ]
 [ 0.6240164 ]
 [ 0.31975654]
 [ 0.57031405]
 [ 0.54293203]
 [ 0.14945202]
 [-0.01348817]]
831 Cost:  0.0050840173 
Prediction:
 [[ 0.9774702 ]
 [ 0.84521306]
 [ 0.6240074 ]
 [ 0.31978515]
 [ 0.5703211 ]
 [ 0.54294115]
 [ 0.14949718]
 [-0.01345119]]
832 Cost:  0.0050831223 
Predicti

884 Cost:  0.005040786 
Prediction:
 [[ 0.97651947]
 [ 0.84303534]
 [ 0.62353265]
 [ 0.3212318 ]
 [ 0.57067525]
 [ 0.5433961 ]
 [ 0.15174298]
 [-0.01164678]]
885 Cost:  0.0050400463 
Prediction:
 [[ 0.97650397]
 [ 0.84299576]
 [ 0.62352395]
 [ 0.3212579 ]
 [ 0.5706817 ]
 [ 0.54340416]
 [ 0.15178272]
 [-0.0116155 ]]
886 Cost:  0.0050393073 
Prediction:
 [[ 0.97648835]
 [ 0.84295636]
 [ 0.62351525]
 [ 0.32128394]
 [ 0.570688  ]
 [ 0.5434123 ]
 [ 0.15182234]
 [-0.01158432]]
887 Cost:  0.0050385734 
Prediction:
 [[ 0.9764731 ]
 [ 0.8429168 ]
 [ 0.6235065 ]
 [ 0.32130992]
 [ 0.57069445]
 [ 0.5434203 ]
 [ 0.15186189]
 [-0.01155322]]
888 Cost:  0.005037846 
Prediction:
 [[ 0.9764577 ]
 [ 0.84287727]
 [ 0.6234977 ]
 [ 0.32133585]
 [ 0.5707009 ]
 [ 0.5434284 ]
 [ 0.15190133]
 [-0.01152223]]
889 Cost:  0.005037114 
Prediction:
 [[ 0.9764424 ]
 [ 0.84283787]
 [ 0.62348896]
 [ 0.32136172]
 [ 0.57070714]
 [ 0.5434364 ]
 [ 0.1519407 ]
 [-0.01149133]]
890 Cost:  0.005036392 
Prediction:
 [[ 0.9764271

 [-0.00987855]]
947 Cost:  0.004998897 
Prediction:
 [[ 0.9756819 ]
 [ 0.84064156]
 [ 0.62299573]
 [ 0.32279238]
 [ 0.5710593 ]
 [ 0.54387635]
 [ 0.15407345]
 [-0.00985269]]
948 Cost:  0.0049983007 
Prediction:
 [[ 0.9756709 ]
 [ 0.84060526]
 [ 0.6229874 ]
 [ 0.3228159 ]
 [ 0.57106507]
 [ 0.54388344]
 [ 0.15410778]
 [-0.00982692]]
949 Cost:  0.0049977098 
Prediction:
 [[ 0.9756598 ]
 [ 0.8405689 ]
 [ 0.62297916]
 [ 0.3228393 ]
 [ 0.57107085]
 [ 0.5438906 ]
 [ 0.15414199]
 [-0.00980122]]
950 Cost:  0.0049971202 
Prediction:
 [[ 0.97564876]
 [ 0.8405326 ]
 [ 0.6229709 ]
 [ 0.32286268]
 [ 0.57107663]
 [ 0.54389775]
 [ 0.15417616]
 [-0.0097756 ]]
951 Cost:  0.0049965302 
Prediction:
 [[ 0.9756378 ]
 [ 0.84049636]
 [ 0.6229626 ]
 [ 0.322886  ]
 [ 0.5710823 ]
 [ 0.54390484]
 [ 0.15421024]
 [-0.00975006]]
952 Cost:  0.004995944 
Prediction:
 [[ 0.9756269 ]
 [ 0.8404602 ]
 [ 0.6229543 ]
 [ 0.32290936]
 [ 0.5710881 ]
 [ 0.54391193]
 [ 0.15424426]
 [-0.00972459]]
953 Cost:  0.004995358 
Predicti

 [-0.00847972]]
1006 Cost:  0.0049669566 
Prediction:
 [[ 0.97512716]
 [ 0.8385779 ]
 [ 0.62252015]
 [ 0.3241137 ]
 [ 0.5713852 ]
 [ 0.5442738 ]
 [ 0.15596996]
 [-0.00845809]]
1007 Cost:  0.0049664667 
Prediction:
 [[ 0.97511923]
 [ 0.83854437]
 [ 0.62251234]
 [ 0.32413504]
 [ 0.57139045]
 [ 0.54428023]
 [ 0.15599999]
 [-0.00843653]]
1008 Cost:  0.0049659754 
Prediction:
 [[ 0.9751114 ]
 [ 0.8385108 ]
 [ 0.6225045 ]
 [ 0.32415634]
 [ 0.57139564]
 [ 0.5442865 ]
 [ 0.1560299 ]
 [-0.00841504]]
1009 Cost:  0.00496549 
Prediction:
 [[ 0.97510386]
 [ 0.8384774 ]
 [ 0.6224967 ]
 [ 0.32417756]
 [ 0.57140094]
 [ 0.54429287]
 [ 0.15605977]
 [-0.00839362]]
1010 Cost:  0.0049650064 
Prediction:
 [[ 0.9750961 ]
 [ 0.8384439 ]
 [ 0.62248886]
 [ 0.32419875]
 [ 0.5714062 ]
 [ 0.5442991 ]
 [ 0.1560896 ]
 [-0.00837225]]
1011 Cost:  0.0049645174 
Prediction:
 [[ 0.9750888 ]
 [ 0.8384105 ]
 [ 0.6224811 ]
 [ 0.32421997]
 [ 0.5714114 ]
 [ 0.5443054 ]
 [ 0.15611932]
 [-0.00835094]]
1012 Cost:  0.004964036 
P

1122 Cost:  0.0049191127 
Prediction:
 [[ 0.97451425]
 [ 0.83497673]
 [ 0.6216639 ]
 [ 0.3263712 ]
 [ 0.57194185]
 [ 0.5449312 ]
 [ 0.1590404 ]
 [-0.00634059]]
1123 Cost:  0.0049187695 
Prediction:
 [[ 0.9745112 ]
 [ 0.8349481 ]
 [ 0.62165695]
 [ 0.32638896]
 [ 0.57194626]
 [ 0.54493624]
 [ 0.15906361]
 [-0.0063253 ]]
1124 Cost:  0.004918426 
Prediction:
 [[ 0.97450817]
 [ 0.8349196 ]
 [ 0.6216501 ]
 [ 0.3264066 ]
 [ 0.5719506 ]
 [ 0.54494125]
 [ 0.15908675]
 [-0.00631006]]
1125 Cost:  0.004918085 
Prediction:
 [[ 0.9745051 ]
 [ 0.8348911 ]
 [ 0.62164325]
 [ 0.32642424]
 [ 0.57195497]
 [ 0.5449464 ]
 [ 0.15910986]
 [-0.00629485]]
1126 Cost:  0.0049177445 
Prediction:
 [[ 0.97450197]
 [ 0.8348626 ]
 [ 0.6216362 ]
 [ 0.32644185]
 [ 0.57195926]
 [ 0.5449514 ]
 [ 0.15913293]
 [-0.0062797 ]]
1127 Cost:  0.0049174065 
Prediction:
 [[ 0.974499  ]
 [ 0.8348341 ]
 [ 0.6216293 ]
 [ 0.32645938]
 [ 0.5719636 ]
 [ 0.5449563 ]
 [ 0.15915592]
 [-0.00626459]]
1128 Cost:  0.0049170656 
Prediction:
 [[ 

1183 Cost:  0.0048998334 
Prediction:
 [[ 0.97437626]
 [ 0.8333021 ]
 [ 0.62125427]
 [ 0.32740143]
 [ 0.5721946 ]
 [ 0.5452208 ]
 [ 0.16036807]
 [-0.00548442]]
1184 Cost:  0.004899543 
Prediction:
 [[ 0.9743749 ]
 [ 0.8332758 ]
 [ 0.62124795]
 [ 0.32741758]
 [ 0.57219857]
 [ 0.5452253 ]
 [ 0.16038844]
 [-0.00547159]]
1185 Cost:  0.0048992564 
Prediction:
 [[ 0.9743735 ]
 [ 0.83324957]
 [ 0.6212414 ]
 [ 0.32743362]
 [ 0.5722025 ]
 [ 0.5452298 ]
 [ 0.16040874]
 [-0.0054588 ]]
1186 Cost:  0.004898968 
Prediction:
 [[ 0.9743721 ]
 [ 0.83322334]
 [ 0.62123483]
 [ 0.32744962]
 [ 0.5722064 ]
 [ 0.5452342 ]
 [ 0.160429  ]
 [-0.00544605]]
1187 Cost:  0.0048986804 
Prediction:
 [[ 0.9743707 ]
 [ 0.83319706]
 [ 0.6212284 ]
 [ 0.3274656 ]
 [ 0.57221025]
 [ 0.5452386 ]
 [ 0.16044922]
 [-0.00543333]]
1188 Cost:  0.004898397 
Prediction:
 [[ 0.9743693 ]
 [ 0.833171  ]
 [ 0.621222  ]
 [ 0.32748163]
 [ 0.57221425]
 [ 0.54524314]
 [ 0.1604694 ]
 [-0.00542065]]
1189 Cost:  0.0048981113 
Prediction:
 [[ 0

 [-0.00475401]]
1246 Cost:  0.004883071 
Prediction:
 [[ 0.97432834]
 [ 0.8317152 ]
 [ 0.6208597 ]
 [ 0.3283674 ]
 [ 0.5724299 ]
 [ 0.5454856 ]
 [ 0.16156942]
 [-0.00474323]]
1247 Cost:  0.0048828255 
Prediction:
 [[ 0.9743282 ]
 [ 0.83169115]
 [ 0.6208536 ]
 [ 0.32838205]
 [ 0.5724334 ]
 [ 0.54548955]
 [ 0.16158724]
 [-0.0047325 ]]
1248 Cost:  0.0048825857 
Prediction:
 [[ 0.9743281 ]
 [ 0.8316671 ]
 [ 0.62084776]
 [ 0.32839662]
 [ 0.57243705]
 [ 0.5454936 ]
 [ 0.161605  ]
 [-0.00472178]]
1249 Cost:  0.0048823436 
Prediction:
 [[ 0.97432816]
 [ 0.8316432 ]
 [ 0.62084174]
 [ 0.32841116]
 [ 0.5724406 ]
 [ 0.54549754]
 [ 0.16162275]
 [-0.0047111 ]]
1250 Cost:  0.004882099 
Prediction:
 [[ 0.974328  ]
 [ 0.83161914]
 [ 0.62083566]
 [ 0.3284257 ]
 [ 0.5724441 ]
 [ 0.54550135]
 [ 0.16164045]
 [-0.00470044]]
1251 Cost:  0.004881861 
Prediction:
 [[ 0.9743278 ]
 [ 0.83159506]
 [ 0.6208296 ]
 [ 0.32844013]
 [ 0.5724476 ]
 [ 0.5455052 ]
 [ 0.16165811]
 [-0.00468982]]
1252 Cost:  0.004881621 
Pr

1303 Cost:  0.0048701395 
Prediction:
 [[ 0.9743484 ]
 [ 0.83039516]
 [ 0.6205268 ]
 [ 0.3291643 ]
 [ 0.5726224 ]
 [ 0.5456987 ]
 [ 0.16252768]
 [-0.00417574]]
1304 Cost:  0.0048699277 
Prediction:
 [[ 0.97434914]
 [ 0.83037287]
 [ 0.6205211 ]
 [ 0.32917768]
 [ 0.5726256 ]
 [ 0.5457022 ]
 [ 0.16254348]
 [-0.00416654]]
1305 Cost:  0.00486972 
Prediction:
 [[ 0.97435   ]
 [ 0.83035064]
 [ 0.6205154 ]
 [ 0.32919094]
 [ 0.5726288 ]
 [ 0.5457056 ]
 [ 0.16255926]
 [-0.00415738]]
1306 Cost:  0.0048695114 
Prediction:
 [[ 0.97435075]
 [ 0.8303285 ]
 [ 0.62050986]
 [ 0.3292043 ]
 [ 0.572632  ]
 [ 0.54570925]
 [ 0.16257504]
 [-0.00414824]]
1307 Cost:  0.0048693004 
Prediction:
 [[ 0.9743517 ]
 [ 0.8303064 ]
 [ 0.6205042 ]
 [ 0.3292176 ]
 [ 0.5726352 ]
 [ 0.54571277]
 [ 0.16259076]
 [-0.00413912]]
1308 Cost:  0.0048690927 
Prediction:
 [[ 0.9743525 ]
 [ 0.83028424]
 [ 0.62049854]
 [ 0.32923093]
 [ 0.5726384 ]
 [ 0.5457162 ]
 [ 0.16260645]
 [-0.00413003]]
1309 Cost:  0.0048688864 
Prediction:
 [[ 

1358 Cost:  0.004859312 
Prediction:
 [[ 0.974411  ]
 [ 0.82921743]
 [ 0.620226  ]
 [ 0.32987025]
 [ 0.5727911 ]
 [ 0.5458828 ]
 [ 0.16335122]
 [-0.00370513]]
1359 Cost:  0.004859127 
Prediction:
 [[ 0.9744124 ]
 [ 0.8291968 ]
 [ 0.6202207 ]
 [ 0.32988253]
 [ 0.57279396]
 [ 0.545886  ]
 [ 0.16336535]
 [-0.0036972 ]]
1360 Cost:  0.004858946 
Prediction:
 [[ 0.9744138 ]
 [ 0.8291763 ]
 [ 0.62021536]
 [ 0.32989478]
 [ 0.5727969 ]
 [ 0.54588914]
 [ 0.16337948]
 [-0.00368927]]
1361 Cost:  0.004858761 
Prediction:
 [[ 0.97441536]
 [ 0.8291558 ]
 [ 0.6202101 ]
 [ 0.32990706]
 [ 0.5727998 ]
 [ 0.5458922 ]
 [ 0.16339354]
 [-0.00368138]]
1362 Cost:  0.004858581 
Prediction:
 [[ 0.97441673]
 [ 0.8291352 ]
 [ 0.62020487]
 [ 0.3299193 ]
 [ 0.5728027 ]
 [ 0.5458954 ]
 [ 0.1634076 ]
 [-0.00367352]]
1363 Cost:  0.004858399 
Prediction:
 [[ 0.9744184 ]
 [ 0.82911474]
 [ 0.62019956]
 [ 0.32993156]
 [ 0.57280564]
 [ 0.54589856]
 [ 0.16342162]
 [-0.00366566]]
1364 Cost:  0.004858217 
Prediction:
 [[ 0.974

 [-0.00327722]]
1417 Cost:  0.0048491904 
Prediction:
 [[ 0.97451353]
 [ 0.8280513 ]
 [ 0.61992466]
 [ 0.3305652 ]
 [ 0.57295495]
 [ 0.5460593 ]
 [ 0.1641379 ]
 [-0.00327039]]
1418 Cost:  0.0048490237 
Prediction:
 [[ 0.9745157 ]
 [ 0.8280323 ]
 [ 0.61991984]
 [ 0.33057645]
 [ 0.57295746]
 [ 0.54606205]
 [ 0.16415043]
 [-0.00326358]]
1419 Cost:  0.004848865 
Prediction:
 [[ 0.97451764]
 [ 0.82801324]
 [ 0.6199148 ]
 [ 0.33058771]
 [ 0.5729601 ]
 [ 0.54606485]
 [ 0.16416293]
 [-0.00325677]]
1420 Cost:  0.0048487056 
Prediction:
 [[ 0.97451943]
 [ 0.82799447]
 [ 0.6199098 ]
 [ 0.33059892]
 [ 0.57296264]
 [ 0.54606766]
 [ 0.16417542]
 [-0.00324998]]
1421 Cost:  0.0048485473 
Prediction:
 [[ 0.9745216 ]
 [ 0.8279756 ]
 [ 0.619905  ]
 [ 0.33061013]
 [ 0.5729653 ]
 [ 0.5460704 ]
 [ 0.1641879 ]
 [-0.00324323]]
1422 Cost:  0.0048483936 
Prediction:
 [[ 0.9745237 ]
 [ 0.82795686]
 [ 0.6199001 ]
 [ 0.33062133]
 [ 0.57296807]
 [ 0.5460733 ]
 [ 0.16420034]
 [-0.00323648]]
1423 Cost:  0.0048482344 

1477 Cost:  0.0048402045 
Prediction:
 [[ 0.9746455 ]
 [ 0.82696056]
 [ 0.6196397 ]
 [ 0.3312119 ]
 [ 0.57310474]
 [ 0.54621875]
 [ 0.16484779]
 [-0.00289001]]
1478 Cost:  0.0048400653 
Prediction:
 [[ 0.9746479 ]
 [ 0.8269431 ]
 [ 0.6196351 ]
 [ 0.3312222 ]
 [ 0.5731071 ]
 [ 0.54622126]
 [ 0.16485891]
 [-0.00288412]]
1479 Cost:  0.004839922 
Prediction:
 [[ 0.9746502 ]
 [ 0.8269257 ]
 [ 0.6196306 ]
 [ 0.33123252]
 [ 0.5731094 ]
 [ 0.54622376]
 [ 0.16487   ]
 [-0.00287826]]
1480 Cost:  0.0048397817 
Prediction:
 [[ 0.9746525 ]
 [ 0.8269083 ]
 [ 0.61962587]
 [ 0.3312428 ]
 [ 0.5731117 ]
 [ 0.54622614]
 [ 0.16488108]
 [-0.00287241]]
1481 Cost:  0.004839644 
Prediction:
 [[ 0.974655  ]
 [ 0.82689106]
 [ 0.6196214 ]
 [ 0.33125305]
 [ 0.5731141 ]
 [ 0.54622877]
 [ 0.16489217]
 [-0.00286658]]
1482 Cost:  0.004839509 
Prediction:
 [[ 0.9746574 ]
 [ 0.82687366]
 [ 0.61961687]
 [ 0.3312633 ]
 [ 0.57311654]
 [ 0.54623127]
 [ 0.16490321]
 [-0.00286075]]
1483 Cost:  0.0048393654 
Prediction:
 [[ 0

1536 Cost:  0.0048324405 
Prediction:
 [[ 0.97479427]
 [ 0.82597446]
 [ 0.6193794 ]
 [ 0.33179453]
 [ 0.5732372 ]
 [ 0.54635805]
 [ 0.16546813]
 [-0.00256625]]
1537 Cost:  0.004832314 
Prediction:
 [[ 0.9747968 ]
 [ 0.8259585 ]
 [ 0.6193751 ]
 [ 0.33180398]
 [ 0.5732392 ]
 [ 0.5463602 ]
 [ 0.16547805]
 [-0.00256114]]
1538 Cost:  0.00483219 
Prediction:
 [[ 0.97479945]
 [ 0.82594246]
 [ 0.619371  ]
 [ 0.33181342]
 [ 0.57324135]
 [ 0.54636246]
 [ 0.16548795]
 [-0.00255604]]
1539 Cost:  0.0048320685 
Prediction:
 [[ 0.974802  ]
 [ 0.8259265 ]
 [ 0.6193666 ]
 [ 0.3318228 ]
 [ 0.57324344]
 [ 0.5463646 ]
 [ 0.16549778]
 [-0.00255096]]
1540 Cost:  0.0048319474 
Prediction:
 [[ 0.97480476]
 [ 0.82591045]
 [ 0.61936235]
 [ 0.3318322 ]
 [ 0.5732456 ]
 [ 0.5463668 ]
 [ 0.16550761]
 [-0.00254588]]
1541 Cost:  0.004831824 
Prediction:
 [[ 0.97480726]
 [ 0.82589453]
 [ 0.6193581 ]
 [ 0.33184162]
 [ 0.5732477 ]
 [ 0.546369  ]
 [ 0.16551745]
 [-0.00254083]]
1542 Cost:  0.0048317034 
Prediction:
 [[ 0.

 [-0.00227943]]
1597 Cost:  0.0048253355 
Prediction:
 [[ 0.97496116]
 [ 0.8250379 ]
 [ 0.6191298 ]
 [ 0.33234638]
 [ 0.57335967]
 [ 0.5464855 ]
 [ 0.16603826]
 [-0.00227497]]
1598 Cost:  0.004825227 
Prediction:
 [[ 0.97496384]
 [ 0.8250232 ]
 [ 0.6191257 ]
 [ 0.332355  ]
 [ 0.5733615 ]
 [ 0.54648745]
 [ 0.16604704]
 [-0.0022705 ]]
1599 Cost:  0.004825117 
Prediction:
 [[ 0.9749667 ]
 [ 0.8250085 ]
 [ 0.61912185]
 [ 0.33236367]
 [ 0.5733634 ]
 [ 0.5464894 ]
 [ 0.16605581]
 [-0.00226607]]
1600 Cost:  0.004825008 
Prediction:
 [[ 0.97496957]
 [ 0.82499385]
 [ 0.619118  ]
 [ 0.33237228]
 [ 0.57336533]
 [ 0.5464914 ]
 [ 0.16606459]
 [-0.00226164]]
1601 Cost:  0.0048248973 
Prediction:
 [[ 0.97497237]
 [ 0.82497936]
 [ 0.6191141 ]
 [ 0.3323809 ]
 [ 0.5733672 ]
 [ 0.54649335]
 [ 0.16607332]
 [-0.00225722]]
1602 Cost:  0.004824792 
Prediction:
 [[ 0.97497535]
 [ 0.82496464]
 [ 0.61911017]
 [ 0.33238947]
 [ 0.57336915]
 [ 0.5464953 ]
 [ 0.16608207]
 [-0.00225281]]
1603 Cost:  0.004824686 
Pre

1650 Cost:  0.0048198067 
Prediction:
 [[ 0.97511286]
 [ 0.8242875 ]
 [ 0.6189279 ]
 [ 0.3327879 ]
 [ 0.5734553 ]
 [ 0.54658407]
 [ 0.16648151]
 [-0.00205181]]
1651 Cost:  0.004819705 
Prediction:
 [[ 0.9751157 ]
 [ 0.8242737 ]
 [ 0.6189242 ]
 [ 0.33279592]
 [ 0.57345694]
 [ 0.54658574]
 [ 0.16648945]
 [-0.00204783]]
1652 Cost:  0.0048196097 
Prediction:
 [[ 0.97511864]
 [ 0.8242602 ]
 [ 0.61892056]
 [ 0.33280393]
 [ 0.57345873]
 [ 0.54658765]
 [ 0.16649738]
 [-0.00204387]]
1653 Cost:  0.004819506 
Prediction:
 [[ 0.97512156]
 [ 0.82424664]
 [ 0.6189168 ]
 [ 0.33281198]
 [ 0.57346034]
 [ 0.5465893 ]
 [ 0.16650528]
 [-0.00203991]]
1654 Cost:  0.004819411 
Prediction:
 [[ 0.97512454]
 [ 0.824233  ]
 [ 0.6189133 ]
 [ 0.33281988]
 [ 0.5734621 ]
 [ 0.5465911 ]
 [ 0.16651317]
 [-0.00203597]]
1655 Cost:  0.0048193093 
Prediction:
 [[ 0.97512746]
 [ 0.82421964]
 [ 0.6189097 ]
 [ 0.33282787]
 [ 0.5734638 ]
 [ 0.54659283]
 [ 0.16652104]
 [-0.00203203]]
1656 Cost:  0.004819214 
Prediction:
 [[ 0.

1709 Cost:  0.004814235 
Prediction:
 [[ 0.97528553]
 [ 0.8235158 ]
 [ 0.61871874]
 [ 0.33324167]
 [ 0.57355076]
 [ 0.5466817 ]
 [ 0.16692442]
 [-0.00183073]]
1710 Cost:  0.004814145 
Prediction:
 [[ 0.97528845]
 [ 0.8235033 ]
 [ 0.6187153 ]
 [ 0.33324894]
 [ 0.57355225]
 [ 0.5466831 ]
 [ 0.16693151]
 [-0.0018272 ]]
1711 Cost:  0.0048140576 
Prediction:
 [[ 0.97529143]
 [ 0.8234907 ]
 [ 0.6187119 ]
 [ 0.3332563 ]
 [ 0.5735538 ]
 [ 0.54668474]
 [ 0.16693857]
 [-0.00182368]]
1712 Cost:  0.0048139663 
Prediction:
 [[ 0.9752943 ]
 [ 0.82347816]
 [ 0.6187085 ]
 [ 0.3332636 ]
 [ 0.57355523]
 [ 0.54668623]
 [ 0.1669456 ]
 [-0.00182017]]
1713 Cost:  0.004813879 
Prediction:
 [[ 0.9752972 ]
 [ 0.8234657 ]
 [ 0.61870503]
 [ 0.33327094]
 [ 0.5735568 ]
 [ 0.5466877 ]
 [ 0.16695264]
 [-0.00181666]]
1714 Cost:  0.00481379 
Prediction:
 [[ 0.9753001 ]
 [ 0.82345325]
 [ 0.6187017 ]
 [ 0.3332783 ]
 [ 0.57355833]
 [ 0.5466893 ]
 [ 0.16695967]
 [-0.00181316]]
1715 Cost:  0.004813699 
Prediction:
 [[ 0.97

1771 Cost:  0.0048089433 
Prediction:
 [[ 0.97546786]
 [ 0.8227716 ]
 [ 0.61851525]
 [ 0.33367926]
 [ 0.5736397 ]
 [ 0.54677165]
 [ 0.16733882]
 [-0.00162428]]
1772 Cost:  0.0048088655 
Prediction:
 [[ 0.97547084]
 [ 0.8227602 ]
 [ 0.61851203]
 [ 0.33368602]
 [ 0.5736411 ]
 [ 0.5467731 ]
 [ 0.1673451 ]
 [-0.00162114]]
1773 Cost:  0.0048087845 
Prediction:
 [[ 0.9754739 ]
 [ 0.8227488 ]
 [ 0.6185089 ]
 [ 0.33369273]
 [ 0.57364243]
 [ 0.54677445]
 [ 0.16735138]
 [-0.00161801]]
1774 Cost:  0.0048087025 
Prediction:
 [[ 0.97547686]
 [ 0.82273734]
 [ 0.61850584]
 [ 0.3336995 ]
 [ 0.5736438 ]
 [ 0.5467758 ]
 [ 0.16735764]
 [-0.00161489]]
1775 Cost:  0.0048086233 
Prediction:
 [[ 0.9754796 ]
 [ 0.822726  ]
 [ 0.6185027 ]
 [ 0.33370614]
 [ 0.5736451 ]
 [ 0.5467771 ]
 [ 0.1673639 ]
 [-0.00161177]]
1776 Cost:  0.0048085414 
Prediction:
 [[ 0.97548264]
 [ 0.82271457]
 [ 0.6184995 ]
 [ 0.33371288]
 [ 0.5736464 ]
 [ 0.5467785 ]
 [ 0.16737013]
 [-0.00160865]]
1777 Cost:  0.0048084576 
Prediction:
 [

1828 Cost:  0.004804507 
Prediction:
 [[ 0.9756342 ]
 [ 0.82214314]
 [ 0.61834186]
 [ 0.33404928]
 [ 0.573712  ]
 [ 0.5468443 ]
 [ 0.1676787 ]
 [-0.00145406]]
1829 Cost:  0.0048044343 
Prediction:
 [[ 0.9756372 ]
 [ 0.8221326 ]
 [ 0.618339  ]
 [ 0.33405554]
 [ 0.5737133 ]
 [ 0.5468455 ]
 [ 0.16768436]
 [-0.00145122]]
1830 Cost:  0.0048043597 
Prediction:
 [[ 0.9756401 ]
 [ 0.82212204]
 [ 0.61833614]
 [ 0.33406174]
 [ 0.5737145 ]
 [ 0.54684675]
 [ 0.16769001]
 [-0.00144837]]
1831 Cost:  0.0048042815 
Prediction:
 [[ 0.975643  ]
 [ 0.8221114 ]
 [ 0.6183331 ]
 [ 0.334068  ]
 [ 0.57371557]
 [ 0.5468479 ]
 [ 0.16769561]
 [-0.00144555]]
1832 Cost:  0.004804209 
Prediction:
 [[ 0.975646  ]
 [ 0.822101  ]
 [ 0.6183303 ]
 [ 0.33407426]
 [ 0.5737169 ]
 [ 0.54684913]
 [ 0.16770123]
 [-0.00144273]]
1833 Cost:  0.0048041325 
Prediction:
 [[ 0.9756489 ]
 [ 0.82209057]
 [ 0.6183273 ]
 [ 0.33408046]
 [ 0.573718  ]
 [ 0.54685026]
 [ 0.16770682]
 [-0.0014399 ]]
1834 Cost:  0.004804064 
Prediction:
 [[ 0

1886 Cost:  0.004800346 
Prediction:
 [[ 0.9758008 ]
 [ 0.82155406]
 [ 0.6181782 ]
 [ 0.33439702]
 [ 0.57377726]
 [ 0.5469093 ]
 [ 0.16798857]
 [-0.00129693]]
1887 Cost:  0.004800275 
Prediction:
 [[ 0.9758037 ]
 [ 0.82154423]
 [ 0.6181754 ]
 [ 0.33440277]
 [ 0.5737782 ]
 [ 0.5469103 ]
 [ 0.16799363]
 [-0.00129435]]
1888 Cost:  0.004800206 
Prediction:
 [[ 0.9758064 ]
 [ 0.8215345 ]
 [ 0.61817265]
 [ 0.33440852]
 [ 0.5737793 ]
 [ 0.54691124]
 [ 0.16799866]
 [-0.00129177]]
1889 Cost:  0.004800138 
Prediction:
 [[ 0.97580916]
 [ 0.8215248 ]
 [ 0.61817   ]
 [ 0.33441424]
 [ 0.57378036]
 [ 0.54691225]
 [ 0.16800368]
 [-0.00128919]]
1890 Cost:  0.004800068 
Prediction:
 [[ 0.9758121 ]
 [ 0.8215149 ]
 [ 0.6181673 ]
 [ 0.33441994]
 [ 0.5737813 ]
 [ 0.5469133 ]
 [ 0.16800867]
 [-0.00128663]]
1891 Cost:  0.004800001 
Prediction:
 [[ 0.97581494]
 [ 0.82150525]
 [ 0.61816454]
 [ 0.33442563]
 [ 0.5737824 ]
 [ 0.54691434]
 [ 0.1680137 ]
 [-0.00128405]]
1892 Cost:  0.0047999304 
Prediction:
 [[ 0.97

1947 Cost:  0.0047962856 
Prediction:
 [[ 0.9759712 ]
 [ 0.8209844 ]
 [ 0.61801857]
 [ 0.3347339 ]
 [ 0.57383704]
 [ 0.5469683 ]
 [ 0.16827938]
 [-0.00114629]]
1948 Cost:  0.004796222 
Prediction:
 [[ 0.97597384]
 [ 0.82097536]
 [ 0.618016  ]
 [ 0.33473912]
 [ 0.5738379 ]
 [ 0.5469691 ]
 [ 0.16828388]
 [-0.00114393]]
1949 Cost:  0.004796156 
Prediction:
 [[ 0.9759766 ]
 [ 0.82096654]
 [ 0.61801344]
 [ 0.33474445]
 [ 0.5738388 ]
 [ 0.54697   ]
 [ 0.16828835]
 [-0.00114157]]
1950 Cost:  0.0047960924 
Prediction:
 [[ 0.9759793 ]
 [ 0.82095754]
 [ 0.618011  ]
 [ 0.3347497 ]
 [ 0.57383966]
 [ 0.5469709 ]
 [ 0.16829282]
 [-0.00113922]]
1951 Cost:  0.004796031 
Prediction:
 [[ 0.9759821 ]
 [ 0.82094866]
 [ 0.6180085 ]
 [ 0.334755  ]
 [ 0.5738407 ]
 [ 0.5469718 ]
 [ 0.16829729]
 [-0.00113686]]
1952 Cost:  0.0047959676 
Prediction:
 [[ 0.97598493]
 [ 0.8209399 ]
 [ 0.618006  ]
 [ 0.33476025]
 [ 0.5738416 ]
 [ 0.54697275]
 [ 0.16830175]
 [-0.00113451]]
1953 Cost:  0.0047959047 
Prediction:
 [[ 0