In [1]:
import tensorflow as tf

/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [6]:
g1 = tf.Graph()
with g1.as_default() as graph:
    
    x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
    y_data = [[152.], [185.], [180.], [196.], [142.]]
    
    X = tf.compat.v1.placeholder(tf.float32, shape=[None, 3])
    Y = tf.compat.v1.placeholder(tf.float32, shape=[None, 1])  
    
    W = tf.Variable(tf.compat.v1.random_normal([3, 1]), name = 'weight')
    b = tf.Variable(tf.compat.v1.random_normal([1]), name = 'bias')
        
    hypothesis = tf.matmul(X, W) + b
  
    cost = tf.reduce_mean(tf.square(hypothesis - Y))
    
    optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=1e-5)
    train = optimizer.minimize(cost)
    
    init_op = tf.compat.v1.global_variables_initializer()
    
sess = tf.compat.v1.Session(graph = g1)

sess.run(init_op)

In [9]:
for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  0.1835632 
Prediction: 
 [[151.38626]
 [184.68309]
 [180.40392]
 [196.5056 ]
 [141.85191]]
10 Cost:  0.1835399 
Prediction: 
 [[151.38634]
 [184.68303]
 [180.40395]
 [196.50552]
 [141.85194]]
20 Cost:  0.18351316 
Prediction: 
 [[151.38641]
 [184.68298]
 [180.40399]
 [196.50543]
 [141.85199]]
30 Cost:  0.18348202 
Prediction: 
 [[151.3865 ]
 [184.68294]
 [180.40402]
 [196.50534]
 [141.852  ]]
40 Cost:  0.18345746 
Prediction: 
 [[151.38658]
 [184.68289]
 [180.40407]
 [196.50526]
 [141.85207]]
50 Cost:  0.18343225 
Prediction: 
 [[151.38666]
 [184.68285]
 [180.4041 ]
 [196.50519]
 [141.8521 ]]
60 Cost:  0.18340077 
Prediction: 
 [[151.38675]
 [184.68282]
 [180.40414]
 [196.5051 ]
 [141.85213]]
70 Cost:  0.18337558 
Prediction: 
 [[151.38683]
 [184.68277]
 [180.40417]
 [196.50502]
 [141.85216]]
80 Cost:  0.18334979 
Prediction: 
 [[151.3869 ]
 [184.68272]
 [180.40422]
 [196.50493]
 [141.85219]]
90 Cost:  0.18332267 
Prediction: 
 [[151.387  ]
 [184.6827 ]
 [180.40427]
 [196.5048

800 Cost:  0.18145241 
Prediction: 
 [[151.39253]
 [184.67969]
 [180.40697]
 [196.49898]
 [141.85493]]
810 Cost:  0.18142377 
Prediction: 
 [[151.39261]
 [184.67964]
 [180.407  ]
 [196.49889]
 [141.85498]]
820 Cost:  0.18140385 
Prediction: 
 [[151.39267]
 [184.67961]
 [180.40703]
 [196.49883]
 [141.85501]]
830 Cost:  0.18137403 
Prediction: 
 [[151.39276]
 [184.67957]
 [180.40707]
 [196.49873]
 [141.85506]]
840 Cost:  0.18134716 
Prediction: 
 [[151.39282]
 [184.67953]
 [180.4071 ]
 [196.49864]
 [141.8551 ]]
850 Cost:  0.18132432 
Prediction: 
 [[151.39291]
 [184.67949]
 [180.40715]
 [196.49858]
 [141.85513]]
860 Cost:  0.18130226 
Prediction: 
 [[151.39297]
 [184.67943]
 [180.40718]
 [196.49849]
 [141.85516]]
870 Cost:  0.18127158 
Prediction: 
 [[151.39307]
 [184.67941]
 [180.40723]
 [196.49841]
 [141.85521]]
880 Cost:  0.18125238 
Prediction: 
 [[151.39311]
 [184.67935]
 [180.40726]
 [196.49832]
 [141.85526]]
890 Cost:  0.18122207 
Prediction: 
 [[151.3932 ]
 [184.67932]
 [180.4072

1660 Cost:  0.1792783 
Prediction: 
 [[151.39868]
 [184.6764 ]
 [180.41002]
 [196.4919 ]
 [141.85852]]
1670 Cost:  0.17925447 
Prediction: 
 [[151.39874]
 [184.67638]
 [180.41006]
 [196.4918 ]
 [141.85857]]
1680 Cost:  0.17922947 
Prediction: 
 [[151.39882]
 [184.67633]
 [180.4101 ]
 [196.49173]
 [141.85861]]
1690 Cost:  0.17919949 
Prediction: 
 [[151.3989 ]
 [184.6763 ]
 [180.41013]
 [196.49164]
 [141.85866]]
1700 Cost:  0.179179 
Prediction: 
 [[151.39896]
 [184.67625]
 [180.41016]
 [196.49156]
 [141.85869]]
1710 Cost:  0.17915522 
Prediction: 
 [[151.39902]
 [184.67622]
 [180.4102 ]
 [196.49147]
 [141.85873]]
1720 Cost:  0.17913023 
Prediction: 
 [[151.3991 ]
 [184.67618]
 [180.41023]
 [196.4914 ]
 [141.85878]]
1730 Cost:  0.17909776 
Prediction: 
 [[151.39917]
 [184.67615]
 [180.41025]
 [196.4913 ]
 [141.85883]]
1740 Cost:  0.17907599 
Prediction: 
 [[151.39925]
 [184.67613]
 [180.41031]
 [196.49124]
 [141.85889]]
1750 Cost:  0.17905354 
Prediction: 
 [[151.39929]
 [184.67607]
 [1

2520 Cost:  0.17720482 
Prediction: 
 [[151.40436]
 [184.67343]
 [180.41293]
 [196.4849 ]
 [141.86234]]
2530 Cost:  0.17717986 
Prediction: 
 [[151.40442]
 [184.6734 ]
 [180.41296]
 [196.4848 ]
 [141.86237]]
2540 Cost:  0.17715256 
Prediction: 
 [[151.4045 ]
 [184.67337]
 [180.413  ]
 [196.48473]
 [141.86243]]
2550 Cost:  0.17713073 
Prediction: 
 [[151.40454]
 [184.67332]
 [180.41301]
 [196.48463]
 [141.86246]]
2560 Cost:  0.17711228 
Prediction: 
 [[151.40462]
 [184.6733 ]
 [180.41307]
 [196.48457]
 [141.8625 ]]
2570 Cost:  0.17707905 
Prediction: 
 [[151.40468]
 [184.67328]
 [180.41309]
 [196.48447]
 [141.86255]]
2580 Cost:  0.17706373 
Prediction: 
 [[151.40474]
 [184.67323]
 [180.41313]
 [196.4844 ]
 [141.8626 ]]
2590 Cost:  0.17703646 
Prediction: 
 [[151.40482]
 [184.6732 ]
 [180.41316]
 [196.48433]
 [141.86266]]
2600 Cost:  0.17701519 
Prediction: 
 [[151.40486]
 [184.67317]
 [180.4132 ]
 [196.48424]
 [141.86269]]
2610 Cost:  0.17699239 
Prediction: 
 [[151.40492]
 [184.67314]


3400 Cost:  0.17516991 
Prediction: 
 [[151.40977]
 [184.67064]
 [180.41574]
 [196.47781]
 [141.86636]]
3410 Cost:  0.17515013 
Prediction: 
 [[151.40984]
 [184.67061]
 [180.41579]
 [196.47774]
 [141.86641]]
3420 Cost:  0.1751299 
Prediction: 
 [[151.4099 ]
 [184.67058]
 [180.41582]
 [196.47768]
 [141.86647]]
3430 Cost:  0.17510292 
Prediction: 
 [[151.40996]
 [184.67055]
 [180.41583]
 [196.47758]
 [141.8665 ]]
3440 Cost:  0.17508024 
Prediction: 
 [[151.41002]
 [184.67052]
 [180.41588]
 [196.4775 ]
 [141.86655]]
3450 Cost:  0.17505656 
Prediction: 
 [[151.41008]
 [184.67047]
 [180.4159 ]
 [196.47742]
 [141.86661]]
3460 Cost:  0.17503479 
Prediction: 
 [[151.41014]
 [184.67046]
 [180.41594]
 [196.47734]
 [141.86665]]
3470 Cost:  0.17500956 
Prediction: 
 [[151.4102 ]
 [184.67043]
 [180.41597]
 [196.47725]
 [141.8667 ]]
3480 Cost:  0.17499016 
Prediction: 
 [[151.41026]
 [184.6704 ]
 [180.416  ]
 [196.47719]
 [141.86674]]
3490 Cost:  0.17496857 
Prediction: 
 [[151.41031]
 [184.67036]
 

4200 Cost:  0.17339471 
Prediction: 
 [[151.4144 ]
 [184.66833]
 [180.41821]
 [196.47148]
 [141.87021]]
4210 Cost:  0.17338192 
Prediction: 
 [[151.41443]
 [184.66827]
 [180.41824]
 [196.47139]
 [141.87024]]
4220 Cost:  0.17335545 
Prediction: 
 [[151.41449]
 [184.66826]
 [180.41826]
 [196.47131]
 [141.87029]]
4230 Cost:  0.17333531 
Prediction: 
 [[151.41455]
 [184.66823]
 [180.4183 ]
 [196.47124]
 [141.87035]]
4240 Cost:  0.17331237 
Prediction: 
 [[151.4146 ]
 [184.6682 ]
 [180.41832]
 [196.47115]
 [141.87038]]
4250 Cost:  0.17329511 
Prediction: 
 [[151.41466]
 [184.66817]
 [180.41837]
 [196.47108]
 [141.87044]]
4260 Cost:  0.17326544 
Prediction: 
 [[151.41472]
 [184.66815]
 [180.4184 ]
 [196.47098]
 [141.87048]]
4270 Cost:  0.17325003 
Prediction: 
 [[151.41476]
 [184.66812]
 [180.41843]
 [196.47092]
 [141.87053]]
4280 Cost:  0.17322358 
Prediction: 
 [[151.41483]
 [184.6681 ]
 [180.41844]
 [196.47084]
 [141.87057]]
4290 Cost:  0.17319885 
Prediction: 
 [[151.41489]
 [184.66808]


 [[151.41899]
 [184.666  ]
 [180.4207 ]
 [196.4648 ]
 [141.87431]]
5060 Cost:  0.17156312 
Prediction: 
 [[151.41905]
 [184.66597]
 [180.42072]
 [196.4647 ]
 [141.87436]]
5070 Cost:  0.17155322 
Prediction: 
 [[151.4191 ]
 [184.66595]
 [180.42078]
 [196.46466]
 [141.87442]]
5080 Cost:  0.17152378 
Prediction: 
 [[151.41916]
 [184.66591]
 [180.42078]
 [196.46455]
 [141.87445]]
5090 Cost:  0.17150314 
Prediction: 
 [[151.41922]
 [184.6659 ]
 [180.4208 ]
 [196.4645 ]
 [141.8745 ]]
5100 Cost:  0.17148173 
Prediction: 
 [[151.41928]
 [184.66588]
 [180.42084]
 [196.46443]
 [141.87456]]
5110 Cost:  0.17146102 
Prediction: 
 [[151.41933]
 [184.66585]
 [180.42087]
 [196.46434]
 [141.8746 ]]
5120 Cost:  0.17144313 
Prediction: 
 [[151.41937]
 [184.66582]
 [180.4209 ]
 [196.46426]
 [141.87465]]
5130 Cost:  0.17142093 
Prediction: 
 [[151.41943]
 [184.66577]
 [180.42093]
 [196.46417]
 [141.8747 ]]
5140 Cost:  0.17140308 
Prediction: 
 [[151.41948]
 [184.66576]
 [180.42096]
 [196.46411]
 [141.87476

5910 Cost:  0.16983461 
Prediction: 
 [[151.42345]
 [184.66379]
 [180.42313]
 [196.45818]
 [141.87851]]
5920 Cost:  0.1698136 
Prediction: 
 [[151.42351]
 [184.66377]
 [180.42316]
 [196.45811]
 [141.87857]]
5930 Cost:  0.16979073 
Prediction: 
 [[151.42355]
 [184.66374]
 [180.42317]
 [196.45802]
 [141.87862]]
5940 Cost:  0.16977657 
Prediction: 
 [[151.4236 ]
 [184.66373]
 [180.42322]
 [196.45796]
 [141.87866]]
5950 Cost:  0.16975299 
Prediction: 
 [[151.42365]
 [184.6637 ]
 [180.42323]
 [196.45787]
 [141.87872]]
5960 Cost:  0.16972642 
Prediction: 
 [[151.42372]
 [184.66368]
 [180.42326]
 [196.4578 ]
 [141.87877]]
5970 Cost:  0.16971247 
Prediction: 
 [[151.42375]
 [184.66365]
 [180.4233 ]
 [196.45772]
 [141.87881]]
5980 Cost:  0.16969149 
Prediction: 
 [[151.42381]
 [184.66364]
 [180.42332]
 [196.45766]
 [141.87888]]
5990 Cost:  0.16967124 
Prediction: 
 [[151.42386]
 [184.6636 ]
 [180.42336]
 [196.45757]
 [141.87892]]
6000 Cost:  0.16965027 
Prediction: 
 [[151.42392]
 [184.66357]
 

6710 Cost:  0.16826245 
Prediction: 
 [[151.42741]
 [184.66187]
 [180.42532]
 [196.45212]
 [141.88248]]
6720 Cost:  0.16824421 
Prediction: 
 [[151.42744]
 [184.66183]
 [180.42534]
 [196.45203]
 [141.8825 ]]
6730 Cost:  0.16822359 
Prediction: 
 [[151.4275 ]
 [184.66182]
 [180.42537]
 [196.45197]
 [141.88257]]
6740 Cost:  0.16820648 
Prediction: 
 [[151.42755]
 [184.66179]
 [180.4254 ]
 [196.45189]
 [141.88261]]
6750 Cost:  0.16818401 
Prediction: 
 [[151.4276 ]
 [184.66176]
 [180.42542]
 [196.4518 ]
 [141.88266]]
6760 Cost:  0.16816464 
Prediction: 
 [[151.42766]
 [184.66177]
 [180.42546]
 [196.45175]
 [141.88272]]
6770 Cost:  0.16814497 
Prediction: 
 [[151.4277 ]
 [184.66173]
 [180.42548]
 [196.45166]
 [141.88275]]
6780 Cost:  0.16813138 
Prediction: 
 [[151.42773]
 [184.6617 ]
 [180.4255 ]
 [196.45158]
 [141.8828 ]]
6790 Cost:  0.1681101 
Prediction: 
 [[151.4278 ]
 [184.66167]
 [180.42554]
 [196.4515 ]
 [141.88286]]
6800 Cost:  0.16809043 
Prediction: 
 [[151.42784]
 [184.66164]
 

7550 Cost:  0.16667718 
Prediction: 
 [[151.4314 ]
 [184.65993]
 [180.42754]
 [196.44585]
 [141.8866 ]]
7560 Cost:  0.16665837 
Prediction: 
 [[151.43144]
 [184.65991]
 [180.42757]
 [196.44577]
 [141.88664]]
7570 Cost:  0.1666396 
Prediction: 
 [[151.43149]
 [184.6599 ]
 [180.4276 ]
 [196.4457 ]
 [141.88669]]
7580 Cost:  0.16662207 
Prediction: 
 [[151.43155]
 [184.65988]
 [180.42763]
 [196.44565]
 [141.88675]]
7590 Cost:  0.1666035 
Prediction: 
 [[151.43158]
 [184.65985]
 [180.42764]
 [196.44556]
 [141.8868 ]]
7600 Cost:  0.1665868 
Prediction: 
 [[151.43163]
 [184.65982]
 [180.42767]
 [196.44548]
 [141.88684]]
7610 Cost:  0.16656658 
Prediction: 
 [[151.43169]
 [184.6598 ]
 [180.4277 ]
 [196.44542]
 [141.8869 ]]
7620 Cost:  0.16655074 
Prediction: 
 [[151.43172]
 [184.65977]
 [180.42772]
 [196.44534]
 [141.88695]]
7630 Cost:  0.1665373 
Prediction: 
 [[151.43176]
 [184.65976]
 [180.42776]
 [196.44528]
 [141.887  ]]
7640 Cost:  0.1665153 
Prediction: 
 [[151.43181]
 [184.65973]
 [180

8340 Cost:  0.1652464 
Prediction: 
 [[151.43501]
 [184.65817]
 [180.42955]
 [196.44006]
 [141.89043]]
8350 Cost:  0.16522983 
Prediction: 
 [[151.43506]
 [184.65817]
 [180.4296 ]
 [196.44   ]
 [141.8905 ]]
8360 Cost:  0.16521493 
Prediction: 
 [[151.43509]
 [184.65814]
 [180.42963]
 [196.43991]
 [141.89053]]
8370 Cost:  0.16519795 
Prediction: 
 [[151.43513]
 [184.65811]
 [180.42964]
 [196.43985]
 [141.8906 ]]
8380 Cost:  0.16517344 
Prediction: 
 [[151.4352 ]
 [184.6581 ]
 [180.42966]
 [196.43977]
 [141.89064]]
8390 Cost:  0.16516033 
Prediction: 
 [[151.43524]
 [184.65808]
 [180.4297 ]
 [196.43971]
 [141.89069]]
8400 Cost:  0.16514067 
Prediction: 
 [[151.43529]
 [184.65805]
 [180.42972]
 [196.43964]
 [141.89075]]
8410 Cost:  0.16512293 
Prediction: 
 [[151.43533]
 [184.65804]
 [180.42975]
 [196.43956]
 [141.89078]]
8420 Cost:  0.16510952 
Prediction: 
 [[151.43536]
 [184.65799]
 [180.42976]
 [196.43948]
 [141.89082]]
8430 Cost:  0.16508752 
Prediction: 
 [[151.43542]
 [184.65799]
 

9180 Cost:  0.16378365 
Prediction: 
 [[151.43872]
 [184.6564 ]
 [180.43167]
 [196.434  ]
 [141.89453]]
9190 Cost:  0.16376558 
Prediction: 
 [[151.43877]
 [184.65639]
 [180.4317 ]
 [196.43393]
 [141.89458]]
9200 Cost:  0.16375037 
Prediction: 
 [[151.4388 ]
 [184.65636]
 [180.43172]
 [196.43385]
 [141.89462]]
9210 Cost:  0.16372941 
Prediction: 
 [[151.43886]
 [184.65636]
 [180.43175]
 [196.43379]
 [141.89467]]
9220 Cost:  0.16371424 
Prediction: 
 [[151.43889]
 [184.65633]
 [180.43176]
 [196.43372]
 [141.89471]]
9230 Cost:  0.16370027 
Prediction: 
 [[151.43893]
 [184.6563 ]
 [180.4318 ]
 [196.43365]
 [141.89478]]
9240 Cost:  0.16368221 
Prediction: 
 [[151.43898]
 [184.65628]
 [180.43182]
 [196.43358]
 [141.89482]]
9250 Cost:  0.16366087 
Prediction: 
 [[151.43903]
 [184.65627]
 [180.43184]
 [196.4335 ]
 [141.89488]]
9260 Cost:  0.16364555 
Prediction: 
 [[151.43907]
 [184.65623]
 [180.43185]
 [196.43344]
 [141.89491]]
9270 Cost:  0.16363005 
Prediction: 
 [[151.43912]
 [184.65623]


10050 Cost:  0.16232666 
Prediction: 
 [[151.44244]
 [184.65463]
 [180.43378]
 [196.42786]
 [141.8987 ]]
10060 Cost:  0.16231306 
Prediction: 
 [[151.44249]
 [184.6546 ]
 [180.4338 ]
 [196.4278 ]
 [141.89876]]
10070 Cost:  0.16229609 
Prediction: 
 [[151.44252]
 [184.65459]
 [180.43382]
 [196.42772]
 [141.8988 ]]
10080 Cost:  0.1622776 
Prediction: 
 [[151.44258]
 [184.65457]
 [180.43385]
 [196.42766]
 [141.89885]]
10090 Cost:  0.1622633 
Prediction: 
 [[151.44261]
 [184.65456]
 [180.43388]
 [196.42758]
 [141.8989 ]]
10100 Cost:  0.16224495 
Prediction: 
 [[151.44266]
 [184.65454]
 [180.4339 ]
 [196.42752]
 [141.89896]]
10110 Cost:  0.16223337 
Prediction: 
 [[151.44269]
 [184.65451]
 [180.43393]
 [196.42744]
 [141.89899]]
10120 Cost:  0.16221502 
Prediction: 
 [[151.44273]
 [184.6545 ]
 [180.43394]
 [196.42738]
 [141.89905]]
10130 Cost:  0.16219604 
Prediction: 
 [[151.4428 ]
 [184.65446]
 [180.43398]
 [196.4273 ]
 [141.8991 ]]
10140 Cost:  0.16217886 
Prediction: 
 [[151.44284]
 [184

10900 Cost:  0.16096589 
Prediction: 
 [[151.446  ]
 [184.65294]
 [180.4358 ]
 [196.42198]
 [141.90271]]
10910 Cost:  0.16094795 
Prediction: 
 [[151.44604]
 [184.65292]
 [180.43584]
 [196.4219 ]
 [141.90277]]
10920 Cost:  0.1609366 
Prediction: 
 [[151.44608]
 [184.6529 ]
 [180.43585]
 [196.42184]
 [141.9028 ]]
10930 Cost:  0.1609191 
Prediction: 
 [[151.44612]
 [184.6529 ]
 [180.43588]
 [196.42178]
 [141.90286]]
10940 Cost:  0.1609012 
Prediction: 
 [[151.44617]
 [184.65286]
 [180.4359 ]
 [196.4217 ]
 [141.90291]]
10950 Cost:  0.16088715 
Prediction: 
 [[151.4462 ]
 [184.65285]
 [180.43591]
 [196.42165]
 [141.90295]]
10960 Cost:  0.16086586 
Prediction: 
 [[151.44626]
 [184.65283]
 [180.43594]
 [196.42157]
 [141.90302]]
10970 Cost:  0.16085449 
Prediction: 
 [[151.44629]
 [184.6528 ]
 [180.43596]
 [196.42151]
 [141.90305]]
10980 Cost:  0.160841 
Prediction: 
 [[151.44632]
 [184.6528 ]
 [180.43599]
 [196.42145]
 [141.90309]]
10990 Cost:  0.16082534 
Prediction: 
 [[151.44637]
 [184.65

11770 Cost:  0.15962657 
Prediction: 
 [[151.4495 ]
 [184.65129]
 [180.43782]
 [196.41606]
 [141.90681]]
11780 Cost:  0.15961279 
Prediction: 
 [[151.44952]
 [184.65128]
 [180.43784]
 [196.416  ]
 [141.90686]]
11790 Cost:  0.15959242 
Prediction: 
 [[151.44958]
 [184.65126]
 [180.43787]
 [196.41592]
 [141.9069 ]]
11800 Cost:  0.15957868 
Prediction: 
 [[151.44962]
 [184.65123]
 [180.43787]
 [196.41586]
 [141.90694]]
11810 Cost:  0.15956113 
Prediction: 
 [[151.44966]
 [184.65121]
 [180.4379 ]
 [196.41579]
 [141.907  ]]
11820 Cost:  0.15955004 
Prediction: 
 [[151.44969]
 [184.6512 ]
 [180.43793]
 [196.41573]
 [141.90704]]
11830 Cost:  0.15953289 
Prediction: 
 [[151.44974]
 [184.65118]
 [180.43794]
 [196.41566]
 [141.90709]]
11840 Cost:  0.15951927 
Prediction: 
 [[151.44977]
 [184.65117]
 [180.43797]
 [196.41559]
 [141.90714]]
11850 Cost:  0.15950552 
Prediction: 
 [[151.4498 ]
 [184.65115]
 [180.43799]
 [196.41553]
 [141.90718]]
11860 Cost:  0.15948585 
Prediction: 
 [[151.44984]
 [1

12580 Cost:  0.15842547 
Prediction: 
 [[151.45268]
 [184.6498 ]
 [180.43964]
 [196.41066]
 [141.91052]]
12590 Cost:  0.15841259 
Prediction: 
 [[151.45274]
 [184.64977]
 [180.43967]
 [196.41061]
 [141.91057]]
12600 Cost:  0.15839389 
Prediction: 
 [[151.45277]
 [184.64975]
 [180.43967]
 [196.41054]
 [141.91061]]
12610 Cost:  0.1583825 
Prediction: 
 [[151.4528 ]
 [184.64973]
 [180.4397 ]
 [196.41048]
 [141.91068]]
12620 Cost:  0.15836637 
Prediction: 
 [[151.45285]
 [184.64972]
 [180.43973]
 [196.4104 ]
 [141.9107 ]]
12630 Cost:  0.15835166 
Prediction: 
 [[151.4529 ]
 [184.64969]
 [180.43974]
 [196.41034]
 [141.91075]]
12640 Cost:  0.15833834 
Prediction: 
 [[151.45293]
 [184.64967]
 [180.43977]
 [196.41026]
 [141.9108 ]]
12650 Cost:  0.15832269 
Prediction: 
 [[151.45296]
 [184.64967]
 [180.43979]
 [196.4102 ]
 [141.91084]]
12660 Cost:  0.15831402 
Prediction: 
 [[151.45299]
 [184.64964]
 [180.43982]
 [196.41014]
 [141.91089]]
12670 Cost:  0.15829718 
Prediction: 
 [[151.45303]
 [18

13470 Cost:  0.15715955 
Prediction: 
 [[151.4561 ]
 [184.6482 ]
 [180.44159]
 [196.40485]
 [141.91455]]
13480 Cost:  0.15715116 
Prediction: 
 [[151.45613]
 [184.64816]
 [180.44162]
 [196.40479]
 [141.9146 ]]
13490 Cost:  0.15713459 
Prediction: 
 [[151.45618]
 [184.64815]
 [180.44164]
 [196.40472]
 [141.91464]]
13500 Cost:  0.15712406 
Prediction: 
 [[151.4562 ]
 [184.64813]
 [180.44167]
 [196.40466]
 [141.91469]]
13510 Cost:  0.1571075 
Prediction: 
 [[151.45625]
 [184.64812]
 [180.44168]
 [196.4046 ]
 [141.91473]]
13520 Cost:  0.15709364 
Prediction: 
 [[151.4563 ]
 [184.6481 ]
 [180.44171]
 [196.40454]
 [141.91478]]
13530 Cost:  0.15707986 
Prediction: 
 [[151.45633]
 [184.64807]
 [180.44171]
 [196.40448]
 [141.91483]]
13540 Cost:  0.15706986 
Prediction: 
 [[151.45636]
 [184.64806]
 [180.44174]
 [196.40442]
 [141.91486]]
13550 Cost:  0.15705088 
Prediction: 
 [[151.4564 ]
 [184.64806]
 [180.44177]
 [196.40434]
 [141.91492]]
13560 Cost:  0.15703982 
Prediction: 
 [[151.45644]
 [18

14390 Cost:  0.15591982 
Prediction: 
 [[151.4595 ]
 [184.64659]
 [180.44357]
 [196.39899]
 [141.91866]]
14400 Cost:  0.15590441 
Prediction: 
 [[151.45953]
 [184.64658]
 [180.44359]
 [196.39891]
 [141.9187 ]]
14410 Cost:  0.15588816 
Prediction: 
 [[151.45958]
 [184.64656]
 [180.4436 ]
 [196.39885]
 [141.91875]]
14420 Cost:  0.15587786 
Prediction: 
 [[151.45961]
 [184.64653]
 [180.44362]
 [196.39879]
 [141.91878]]
14430 Cost:  0.15586187 
Prediction: 
 [[151.45966]
 [184.64651]
 [180.44365]
 [196.39871]
 [141.91882]]
14440 Cost:  0.15584894 
Prediction: 
 [[151.45969]
 [184.6465 ]
 [180.44366]
 [196.39865]
 [141.91887]]
14450 Cost:  0.15583895 
Prediction: 
 [[151.45972]
 [184.6465 ]
 [180.4437 ]
 [196.3986 ]
 [141.91891]]
14460 Cost:  0.15582487 
Prediction: 
 [[151.45976]
 [184.64647]
 [180.44371]
 [196.39854]
 [141.91896]]
14470 Cost:  0.15581515 
Prediction: 
 [[151.4598 ]
 [184.64645]
 [180.44374]
 [196.39848]
 [141.91899]]
14480 Cost:  0.15579863 
Prediction: 
 [[151.45984]
 [1

15260 Cost:  0.15479052 
Prediction: 
 [[151.46268]
 [184.64511]
 [180.4454 ]
 [196.39355]
 [141.92241]]
15270 Cost:  0.15477999 
Prediction: 
 [[151.4627 ]
 [184.64508]
 [180.44542]
 [196.3935 ]
 [141.92245]]
15280 Cost:  0.15476671 
Prediction: 
 [[151.46275]
 [184.64507]
 [180.44545]
 [196.39343]
 [141.9225 ]]
15290 Cost:  0.15475163 
Prediction: 
 [[151.46278]
 [184.64505]
 [180.44547]
 [196.39336]
 [141.92255]]
15300 Cost:  0.15473804 
Prediction: 
 [[151.46283]
 [184.64503]
 [180.44548]
 [196.39331]
 [141.92259]]
15310 Cost:  0.15472887 
Prediction: 
 [[151.46284]
 [184.645  ]
 [180.4455 ]
 [196.39323]
 [141.92262]]
15320 Cost:  0.15471539 
Prediction: 
 [[151.4629 ]
 [184.64502]
 [180.44556]
 [196.39319]
 [141.92268]]
15330 Cost:  0.15470216 
Prediction: 
 [[151.46294]
 [184.64499]
 [180.44556]
 [196.39313]
 [141.92273]]
15340 Cost:  0.15469538 
Prediction: 
 [[151.46295]
 [184.64496]
 [180.44557]
 [196.39307]
 [141.92276]]
15350 Cost:  0.15467726 
Prediction: 
 [[151.463  ]
 [1

16140 Cost:  0.15370187 
Prediction: 
 [[151.4658 ]
 [184.64363]
 [180.44722]
 [196.38818]
 [141.92615]]
16150 Cost:  0.15368488 
Prediction: 
 [[151.46584]
 [184.64363]
 [180.44724]
 [196.3881 ]
 [141.9262 ]]
16160 Cost:  0.15367374 
Prediction: 
 [[151.46588]
 [184.6436 ]
 [180.44725]
 [196.38806]
 [141.92624]]
16170 Cost:  0.15365893 
Prediction: 
 [[151.46591]
 [184.64359]
 [180.44727]
 [196.38799]
 [141.92628]]
16180 Cost:  0.15365377 
Prediction: 
 [[151.46594]
 [184.64355]
 [180.4473 ]
 [196.38794]
 [141.92633]]
16190 Cost:  0.1536396 
Prediction: 
 [[151.46597]
 [184.64355]
 [180.44731]
 [196.38788]
 [141.92636]]
16200 Cost:  0.15362428 
Prediction: 
 [[151.46602]
 [184.64354]
 [180.44734]
 [196.3878 ]
 [141.9264 ]]
16210 Cost:  0.15361501 
Prediction: 
 [[151.46603]
 [184.64351]
 [180.44734]
 [196.38774]
 [141.92644]]
16220 Cost:  0.1536018 
Prediction: 
 [[151.46608]
 [184.64351]
 [180.44737]
 [196.3877 ]
 [141.9265 ]]
16230 Cost:  0.15358886 
Prediction: 
 [[151.46613]
 [184

16970 Cost:  0.15270774 
Prediction: 
 [[151.46866]
 [184.6423 ]
 [180.44887]
 [196.3832 ]
 [141.92966]]
16980 Cost:  0.15269871 
Prediction: 
 [[151.46869]
 [184.64229]
 [180.4489 ]
 [196.38313]
 [141.92969]]
16990 Cost:  0.15268326 
Prediction: 
 [[151.46873]
 [184.64227]
 [180.44891]
 [196.38307]
 [141.92973]]
17000 Cost:  0.1526734 
Prediction: 
 [[151.46877]
 [184.64226]
 [180.44893]
 [196.38303]
 [141.92978]]
17010 Cost:  0.15266147 
Prediction: 
 [[151.4688 ]
 [184.64223]
 [180.44894]
 [196.38295]
 [141.92981]]
17020 Cost:  0.15264983 
Prediction: 
 [[151.46883]
 [184.64223]
 [180.44897]
 [196.38289]
 [141.92986]]
17030 Cost:  0.15263765 
Prediction: 
 [[151.46886]
 [184.64221]
 [180.44899]
 [196.38283]
 [141.9299 ]]
17040 Cost:  0.15262222 
Prediction: 
 [[151.4689 ]
 [184.6422 ]
 [180.449  ]
 [196.38277]
 [141.92995]]
17050 Cost:  0.1526154 
Prediction: 
 [[151.46893]
 [184.64217]
 [180.44902]
 [196.38272]
 [141.92996]]
17060 Cost:  0.15260553 
Prediction: 
 [[151.46896]
 [184

17830 Cost:  0.15172341 
Prediction: 
 [[151.47159]
 [184.64093]
 [180.45056]
 [196.37814]
 [141.93315]]
17840 Cost:  0.15171638 
Prediction: 
 [[151.47162]
 [184.6409 ]
 [180.45059]
 [196.37808]
 [141.9332 ]]
17850 Cost:  0.15170132 
Prediction: 
 [[151.47166]
 [184.6409 ]
 [180.4506 ]
 [196.37804]
 [141.93324]]
17860 Cost:  0.15168977 
Prediction: 
 [[151.4717 ]
 [184.64088]
 [180.45062]
 [196.37798]
 [141.93327]]
17870 Cost:  0.15167521 
Prediction: 
 [[151.47173]
 [184.64088]
 [180.45064]
 [196.37791]
 [141.93333]]
17880 Cost:  0.15166509 
Prediction: 
 [[151.47177]
 [184.64087]
 [180.45067]
 [196.37787]
 [141.93338]]
17890 Cost:  0.15165575 
Prediction: 
 [[151.4718 ]
 [184.64084]
 [180.45068]
 [196.3778 ]
 [141.93341]]
17900 Cost:  0.15164787 
Prediction: 
 [[151.47182]
 [184.64082]
 [180.45071]
 [196.37773]
 [141.93344]]
17910 Cost:  0.151635 
Prediction: 
 [[151.47186]
 [184.64081]
 [180.45073]
 [196.37769]
 [141.93349]]
17920 Cost:  0.15162118 
Prediction: 
 [[151.4719 ]
 [184

18670 Cost:  0.15080138 
Prediction: 
 [[151.47437]
 [184.63963]
 [180.45218]
 [196.3733 ]
 [141.93654]]
18680 Cost:  0.15078606 
Prediction: 
 [[151.47441]
 [184.63962]
 [180.4522 ]
 [196.37325]
 [141.9366 ]]
18690 Cost:  0.15077746 
Prediction: 
 [[151.47444]
 [184.6396 ]
 [180.45222]
 [196.37318]
 [141.93663]]
18700 Cost:  0.15076934 
Prediction: 
 [[151.47446]
 [184.63959]
 [180.45224]
 [196.37312]
 [141.93666]]
18710 Cost:  0.15076172 
Prediction: 
 [[151.4745 ]
 [184.63957]
 [180.45227]
 [196.3731 ]
 [141.9367 ]]
18720 Cost:  0.15074535 
Prediction: 
 [[151.47453]
 [184.63956]
 [180.45227]
 [196.37302]
 [141.93674]]
18730 Cost:  0.15073961 
Prediction: 
 [[151.47455]
 [184.63954]
 [180.4523 ]
 [196.37296]
 [141.93678]]
18740 Cost:  0.1507223 
Prediction: 
 [[151.4746 ]
 [184.63953]
 [180.4523 ]
 [196.3729 ]
 [141.93681]]
18750 Cost:  0.15071525 
Prediction: 
 [[151.47462]
 [184.63951]
 [180.45233]
 [196.37285]
 [141.93687]]
18760 Cost:  0.15070072 
Prediction: 
 [[151.47467]
 [18

19590 Cost:  0.14983416 
Prediction: 
 [[151.47733]
 [184.63824]
 [180.4539 ]
 [196.36812]
 [141.9402 ]]
19600 Cost:  0.14982006 
Prediction: 
 [[151.47737]
 [184.63824]
 [180.45393]
 [196.36806]
 [141.94025]]
19610 Cost:  0.14980611 
Prediction: 
 [[151.4774 ]
 [184.63821]
 [180.45393]
 [196.36798]
 [141.94028]]
19620 Cost:  0.14980006 
Prediction: 
 [[151.47743]
 [184.63821]
 [180.45396]
 [196.36795]
 [141.9403 ]]
19630 Cost:  0.14978859 
Prediction: 
 [[151.47746]
 [184.6382 ]
 [180.45398]
 [196.36789]
 [141.94035]]
19640 Cost:  0.14977992 
Prediction: 
 [[151.4775 ]
 [184.6382 ]
 [180.45401]
 [196.36784]
 [141.9404 ]]
19650 Cost:  0.149771 
Prediction: 
 [[151.47752]
 [184.63815]
 [180.45403]
 [196.36777]
 [141.94043]]
19660 Cost:  0.14975956 
Prediction: 
 [[151.47755]
 [184.63815]
 [180.45404]
 [196.36772]
 [141.94048]]
19670 Cost:  0.14974847 
Prediction: 
 [[151.47758]
 [184.63814]
 [180.45406]
 [196.36766]
 [141.9405 ]]
19680 Cost:  0.14973882 
Prediction: 
 [[151.47763]
 [184